FROM node:22.13.1-slim
WORKDIR /app

# Instalar dependencias
COPY package.json package-lock.json ./
RUN --mount=type=cache,target=/root/.npm npm install

# Copiar código
COPY . .

ENV CHOKIDAR_USEPOLLING=true
ENV FAST_REFRESH=true
ENV DISABLE_ESLINT_PLUGIN=true
ENV GENERATE_SOURCEMAP=false

EXPOSE 3000
CMD ["npm", "start"]

