services:
  python-backend:
    image: joserafael1990/medical-records-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      - APP_ENV=development
      - GCP_PROJECT_ID=lofty-reserve-479620-a3
      - GCP_REGION=us-central1
      - GEMINI_BOT_ENABLED=true
      - GEMINI_MODEL=gemini-2.0-flash-lite
      - GOOGLE_APPLICATION_CREDENTIALS=/app/.gcloud/application_default_credentials.json
    volumes:
      - ~/.config/gcloud:/app/.gcloud:ro

  typescript-frontend:
    image: joserafael1990/medical-records-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
