# Docker Compose for Production (Doppler + Docker Hub Images)
# Usage: doppler run --project cortex --config prd -- docker compose -f compose.prod.yaml up -d

services:
  python-backend:
    # Use pre-built image from Docker Hub

    image: joserafael1990/medical-records-backend:latest
    restart: always
    init: true
    expose:
      - "8000"
    
    # --- ARREGLO 1: CONEXIÓN DE RED (IMPORTANTE) ---
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.python-backend.loadbalancer.server.port=8000"
    # -----------------------------------------------

    networks:
      - appnet
    
    # --- ARREGLO 2: HEALTHCHECK DESACTIVADO (IMPORTANTE) ---
    # Comentado temporalmente para evitar que Coolify reinicie el contenedor
    # hasta que agregues la ruta /health en tu código Python.
    # healthcheck:
    #   test: [ "CMD-SHELL", "curl -f http://localhost:8000/health || exit 1" ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    # -------------------------------------------------------

    environment:
      # Variables injected by Doppler
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SENTRY_DSN_BACKEND=${SENTRY_DSN_BACKEND}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-production}
      - ENABLE_ENCRYPTION=${ENABLE_ENCRYPTION:-true}
      - SECURITY_HEADERS_ENABLED=${SECURITY_HEADERS_ENABLED:-true}
      - CONTENT_SECURITY_POLICY=${CONTENT_SECURITY_POLICY}
      - RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED:-true}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-120}
      - RATE_LIMIT_WINDOW_SECONDS=${RATE_LIMIT_WINDOW_SECONDS:-60}
      - MEDICAL_ENCRYPTION_KEY=${MEDICAL_ENCRYPTION_KEY}
      - WHATSAPP_PROVIDER=${WHATSAPP_PROVIDER:-meta}
      - META_WHATSAPP_PHONE_ID=${META_WHATSAPP_PHONE_ID}
      - META_WHATSAPP_TOKEN=${META_WHATSAPP_TOKEN}
      - META_WHATSAPP_API_VERSION=${META_WHATSAPP_API_VERSION:-v24.0}
      - APP_ENV=${APP_ENV:-production}
      
      # --- ARREGLO 3: CORS MANUAL (EVITA EL CRASH) ---
      # Sin comillas simples alrededor, solo corchetes y comillas dobles internas
      - CORS_ORIGINS=["https://sistema.cortexclinico.com","https://api.cortexclinico.com"]
      # -----------------------------------------------

      - META_WHATSAPP_APP_SECRET=${META_WHATSAPP_APP_SECRET}
      - META_WHATSAPP_VERIFY_TOKEN=${META_WHATSAPP_VERIFY_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    depends_on:
      - postgres-db

  typescript-frontend:
    # Use pre-built image from Docker Hub
    image: joserafael1990/medical-records-frontend:latest

    restart: always
    init: true
    ports:
      - "3000:3000"
    networks:
      - appnet
    environment:
      - REACT_APP_SENTRY_DSN=${REACT_APP_SENTRY_DSN}
      - REACT_APP_SENTRY_ENVIRONMENT=${REACT_APP_SENTRY_ENVIRONMENT:-production}
      - REACT_APP_AMPLITUDE_API_KEY=${REACT_APP_AMPLITUDE_API_KEY}
    depends_on:
      - python-backend
    deploy:
      resources:
        limits:
          memory: 2G # Lower memory limit for production (static files)

  postgres-db:
    image: postgres:15-alpine
    restart: always
    networks:
      - appnet
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-historias_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-historias_pass}
      POSTGRES_DB: ${POSTGRES_DB:-historias_clinicas}
    ports:
      - "5432:5432" # Standard port for production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-historias_user} -d ${POSTGRES_DB:-historias_clinicas}" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  appnet:
    driver: bridge

volumes:
  postgres_data: