# Docker Compose for Production (Coolify)
# Usage: docker compose -f compose.prod.yaml up -d
# Environment variables are injected by Coolify

services:
  # CORREGIDO: Ahora tiene los 2 espacios de sangría necesarios
  python-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    init: true
    expose:
      - "8000"

    # Etiquetas para que Coolify (Traefik) encuentre el puerto correcto
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.python-backend.loadbalancer.server.port=8000"

    networks:
      - appnet

    # --- HEALTHCHECK (Paso 2) ---
    # Mantenlo comentado por ahora. Cuando agregues @app.get("/health") en tu Python,
    # quita los símbolos '#' de las siguientes 6 líneas:
    # healthcheck:
    #   test: [ "CMD-SHELL", "curl -f http://localhost:8000/health || exit 1" ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    # -----------------------------

    environment:
      # Variables injected by Coolify
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SENTRY_DSN_BACKEND=${SENTRY_DSN_BACKEND}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-production}
      - ENABLE_ENCRYPTION=${ENABLE_ENCRYPTION:-true}
      - SECURITY_HEADERS_ENABLED=${SECURITY_HEADERS_ENABLED:-true}
      - CONTENT_SECURITY_POLICY=${CONTENT_SECURITY_POLICY}
      - RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED:-true}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-120}
      - RATE_LIMIT_WINDOW_SECONDS=${RATE_LIMIT_WINDOW_SECONDS:-60}
      - MEDICAL_ENCRYPTION_KEY=${MEDICAL_ENCRYPTION_KEY}
      - WHATSAPP_PROVIDER=${WHATSAPP_PROVIDER:-meta}
      - META_WHATSAPP_PHONE_ID=${META_WHATSAPP_PHONE_ID}
      - META_WHATSAPP_TOKEN=${META_WHATSAPP_TOKEN}
      - META_WHATSAPP_API_VERSION=${META_WHATSAPP_API_VERSION:-v24.0}
      - APP_ENV=${APP_ENV:-production}

      # CORS configuration - supports both JSON array and comma-separated formats
      # Recommended format: comma-separated (no brackets/quotes needed)
      # Example: https://sistema.cortexclinico.com,https://api.cortexclinico.com
      # Alternative: JSON array format ["https://sistema.cortexclinico.com", "https://api.cortexclinico.com"]
      - CORS_ORIGINS=${CORS_ORIGINS:-https://sistema.cortexclinico.com}
      - DATABASE_URL=${DATABASE_URL}

      - META_WHATSAPP_APP_SECRET=${META_WHATSAPP_APP_SECRET}
      - META_WHATSAPP_VERIFY_TOKEN=${META_WHATSAPP_VERIFY_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    depends_on:
      - postgres-db

  typescript-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Build-time variables needed for React
        - REACT_APP_API_URL=${REACT_APP_API_URL}
        - REACT_APP_SENTRY_DSN=${REACT_APP_SENTRY_DSN}
        - REACT_APP_SENTRY_ENVIRONMENT=${REACT_APP_SENTRY_ENVIRONMENT:-production}
        - REACT_APP_AMPLITUDE_API_KEY=${REACT_APP_AMPLITUDE_API_KEY}
    restart: always
    init: true
    expose:
      - "3000"
    
    # Etiquetas para que Coolify (Traefik) encuentre el puerto correcto
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.typescript-frontend.loadbalancer.server.port=3000"
    
    networks:
      - appnet
    environment:
      # Runtime variables (if needed by serve or other tools)
      - NODE_ENV=production
    depends_on:
      - python-backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M # Limite bajo porque son archivos estáticos

  postgres-db:
    image: postgres:15-alpine
    restart: always
    networks:
      - appnet
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432" # Standard port for production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-historias_user} -d ${POSTGRES_DB:-historias_clinicas}" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  appnet:
    driver: bridge

volumes:
  postgres_data:
