-- ============================================================================
-- ESTUDIOS CLÍNICOS - CATÁLOGO
-- ============================================================================
-- Insertar 500 estudios clínicos comunes distribuidos en diversas categorías

INSERT INTO study_catalog (id, name, category_id, is_active, created_at, updated_at) VALUES
-- HEMATOLOGÍA (1)
(1, 'Hemograma Completo', 1, true, NOW(), NOW()),
(2, 'Biometría Hemática', 1, true, NOW(), NOW()),
(3, 'Recuento de Plaquetas', 1, true, NOW(), NOW()),
(4, 'Frotis de Sangre Periférica', 1, true, NOW(), NOW()),
(5, 'Velocidad de Sedimentación Globular (VSG)', 1, true, NOW(), NOW()),
(6, 'Proteína C Reactiva (PCR)', 1, true, NOW(), NOW()),
(7, 'Tiempo de Protrombina (TP)', 1, true, NOW(), NOW()),
(8, 'Tiempo de Tromboplastina Parcial (TTP)', 1, true, NOW(), NOW()),
(9, 'Fibrinógeno', 1, true, NOW(), NOW()),
(10, 'Ferritina', 1, true, NOW(), NOW()),
(11, 'Transferrina', 1, true, NOW(), NOW()),
(12, 'Saturación de Transferrina', 1, true, NOW(), NOW()),
(13, 'Electroforesis de Hemoglobina', 1, true, NOW(), NOW()),
(14, 'Reticulocitos', 1, true, NOW(), NOW()),
(15, 'Coagulación Completa', 1, true, NOW(), NOW()),
(16, 'Anticoagulante Lúpico', 1, true, NOW(), NOW()),
(17, 'Dímero D', 1, true, NOW(), NOW()),
(18, 'Antitrombina III', 1, true, NOW(), NOW()),
(19, 'Factor de von Willebrand', 1, true, NOW(), NOW()),
(20, 'Haptoglobina', 1, true, NOW(), NOW()),

-- QUÍMICA SANGUÍNEA (2)
(21, 'Glucosa en Ayunas', 2, true, NOW(), NOW()),
(22, 'Glucosa Postprandial', 2, true, NOW(), NOW()),
(23, 'Hemoglobina Glicosilada (HbA1c)', 2, true, NOW(), NOW()),
(24, 'Perfil Lipídico Completo', 2, true, NOW(), NOW()),
(25, 'Colesterol Total', 2, true, NOW(), NOW()),
(26, 'Colesterol HDL', 2, true, NOW(), NOW()),
(27, 'Colesterol LDL', 2, true, NOW(), NOW()),
(28, 'Triglicéridos', 2, true, NOW(), NOW()),
(29, 'Perfil Hepático Completo', 2, true, NOW(), NOW()),
(30, 'Transaminasa GPT (ALT)', 2, true, NOW(), NOW()),
(31, 'Transaminasa GOT (AST)', 2, true, NOW(), NOW()),
(32, 'Fosfatasa Alcalina', 2, true, NOW(), NOW()),
(33, 'Bilirrubina Total', 2, true, NOW(), NOW()),
(34, 'Bilirrubina Directa', 2, true, NOW(), NOW()),
(35, 'Bilirrubina Indirecta', 2, true, NOW(), NOW()),
(36, 'Gamma Glutamil Transferasa (GGT)', 2, true, NOW(), NOW()),
(37, 'Perfil Renal Completo', 2, true, NOW(), NOW()),
(38, 'Urea', 2, true, NOW(), NOW()),
(39, 'Creatinina', 2, true, NOW(), NOW()),
(40, 'Ácido Úrico', 2, true, NOW(), NOW()),
(41, 'Depuración de Creatinina', 2, true, NOW(), NOW()),
(42, 'Microalbuminuria', 2, true, NOW(), NOW()),
(43, 'Proteínas Totales', 2, true, NOW(), NOW()),
(44, 'Albumina', 2, true, NOW(), NOW()),
(45, 'Globulinas', 2, true, NOW(), NOW()),
(46, 'Electrolitos Séricos', 2, true, NOW(), NOW()),
(47, 'Sodio', 2, true, NOW(), NOW()),
(48, 'Potasio', 2, true, NOW(), NOW()),
(49, 'Cloro', 2, true, NOW(), NOW()),
(50, 'Calcio', 2, true, NOW(), NOW()),
(51, 'Fósforo', 2, true, NOW(), NOW()),
(52, 'Magnesio', 2, true, NOW(), NOW()),
(53, 'Amilasa', 2, true, NOW(), NOW()),
(54, 'Lipasa', 2, true, NOW(), NOW()),
(55, 'Lactato Deshidrogenasa (LDH)', 2, true, NOW(), NOW()),
(56, 'Creatina Quinasa (CK)', 2, true, NOW(), NOW()),
(57, 'Troponina I', 2, true, NOW(), NOW()),
(58, 'Troponina T', 2, true, NOW(), NOW()),
(59, 'BNP (Péptido Natriurético Cerebral)', 2, true, NOW(), NOW()),
(60, 'Ácido Láctico', 2, true, NOW(), NOW()),

-- MICROBIOLOGÍA (3)
(61, 'Cultivo de Orina', 3, true, NOW(), NOW()),
(62, 'Urocultivo con Antibiograma', 3, true, NOW(), NOW()),
(63, 'Cultivo de Esputo', 3, true, NOW(), NOW()),
(64, 'Cultivo de Secreción Faríngea', 3, true, NOW(), NOW()),
(65, 'Cultivo de Herida', 3, true, NOW(), NOW()),
(66, 'Cultivo de Sangre (Hemocultivo)', 3, true, NOW(), NOW()),
(67, 'Cultivo de Líquido Cefalorraquídeo', 3, true, NOW(), NOW()),
(68, 'Cultivo de Heces', 3, true, NOW(), NOW()),
(69, 'Parasitológico en Heces', 3, true, NOW(), NOW()),
(70, 'Cultivo de Exudado Vaginal', 3, true, NOW(), NOW()),
(71, 'Cultivo de Exudado Uretral', 3, true, NOW(), NOW()),
(72, 'Tinción de Gram', 3, true, NOW(), NOW()),
(73, 'Ziehl-Neelsen (BK)', 3, true, NOW(), NOW()),
(74, 'Prueba de Sensibilidad Antimicrobiana', 3, true, NOW(), NOW()),
(75, 'Antibiograma', 3, true, NOW(), NOW()),
(76, 'Cultivo de Hongos', 3, true, NOW(), NOW()),
(77, 'Cultivo de Micobacterias', 3, true, NOW(), NOW()),
(78, 'Prueba de Clamidia', 3, true, NOW(), NOW()),
(79, 'Prueba de Gonorrea', 3, true, NOW(), NOW()),
(80, 'Cultivo de Virus', 3, true, NOW(), NOW()),

-- INMUNOLOGÍA (4)
(81, 'Anticuerpos Antinucleares (ANA)', 4, true, NOW(), NOW()),
(82, 'Factor Reumatoide', 4, true, NOW(), NOW()),
(83, 'Anticuerpos Anti-ADN', 4, true, NOW(), NOW()),
(84, 'Anticuerpos Anti-Sm', 4, true, NOW(), NOW()),
(85, 'Anticuerpos Anti-Ro (SSA)', 4, true, NOW(), NOW()),
(86, 'Anticuerpos Anti-La (SSB)', 4, true, NOW(), NOW()),
(87, 'Anticuerpos Anticardiolipina', 4, true, NOW(), NOW()),
(88, 'Complemento C3', 4, true, NOW(), NOW()),
(89, 'Complemento C4', 4, true, NOW(), NOW()),
(90, 'Inmunoglobulinas (IgG, IgA, IgM)', 4, true, NOW(), NOW()),
(91, 'Inmunoglobulina E (IgE)', 4, true, NOW(), NOW()),
(92, 'Prueba de Alergias', 4, true, NOW(), NOW()),
(93, 'Panel de Alergias Alimentarias', 4, true, NOW(), NOW()),
(94, 'Panel de Alergias Ambientales', 4, true, NOW(), NOW()),
(95, 'Prueba de Celiaquía (Anti-transglutaminasa)', 4, true, NOW(), NOW()),
(96, 'Anticuerpos Antimicrosomales', 4, true, NOW(), NOW()),
(97, 'Anticuerpos Antitiroglobulina', 4, true, NOW(), NOW()),
(98, 'Anticuerpos Antiperoxidasa', 4, true, NOW(), NOW()),
(99, 'Prueba de VIH', 4, true, NOW(), NOW()),
(100, 'Prueba de Hepatitis B', 4, true, NOW(), NOW()),
(101, 'Prueba de Hepatitis C', 4, true, NOW(), NOW()),
(102, 'Prueba de Hepatitis A', 4, true, NOW(), NOW()),
(103, 'Prueba de Sífilis (VDRL)', 4, true, NOW(), NOW()),
(104, 'Prueba de Toxoplasmosis', 4, true, NOW(), NOW()),
(105, 'Prueba de Rubéola', 4, true, NOW(), NOW()),
(106, 'Prueba de Citomegalovirus (CMV)', 4, true, NOW(), NOW()),
(107, 'Prueba de Herpes Simple', 4, true, NOW(), NOW()),
(108, 'Prueba de Varicela Zóster', 4, true, NOW(), NOW()),
(109, 'Prueba de Mononucleosis', 4, true, NOW(), NOW()),
(110, 'Prueba de Brucelosis', 4, true, NOW(), NOW()),

-- RADIOLOGÍA (5)
(111, 'Radiografía de Tórax PA y Lateral', 5, true, NOW(), NOW()),
(112, 'Radiografía de Tórax AP', 5, true, NOW(), NOW()),
(113, 'Radiografía de Abdomen', 5, true, NOW(), NOW()),
(114, 'Radiografía de Columna Lumbar', 5, true, NOW(), NOW()),
(115, 'Radiografía de Columna Cervical', 5, true, NOW(), NOW()),
(116, 'Radiografía de Columna Dorsal', 5, true, NOW(), NOW()),
(117, 'Radiografía de Cráneo', 5, true, NOW(), NOW()),
(118, 'Radiografía de Hombro', 5, true, NOW(), NOW()),
(119, 'Radiografía de Codo', 5, true, NOW(), NOW()),
(120, 'Radiografía de Muñeca', 5, true, NOW(), NOW()),
(121, 'Radiografía de Mano', 5, true, NOW(), NOW()),
(122, 'Radiografía de Cadera', 5, true, NOW(), NOW()),
(123, 'Radiografía de Rodilla', 5, true, NOW(), NOW()),
(124, 'Radiografía de Tobillo', 5, true, NOW(), NOW()),
(125, 'Radiografía de Pie', 5, true, NOW(), NOW()),
(126, 'Radiografía de Senos Paranasales', 5, true, NOW(), NOW()),
(127, 'Radiografía de Mandíbula', 5, true, NOW(), NOW()),
(128, 'Radiografía de Pelvis', 5, true, NOW(), NOW()),
(129, 'Serie Ósea', 5, true, NOW(), NOW()),
(130, 'Radiografía de Abdomen con Contraste', 5, true, NOW(), NOW()),

-- ULTRASONIDO (6)
(131, 'Ultrasonido Abdominal Completo', 6, true, NOW(), NOW()),
(132, 'Ultrasonido de Hígado', 6, true, NOW(), NOW()),
(133, 'Ultrasonido de Vesícula Biliar', 6, true, NOW(), NOW()),
(134, 'Ultrasonido de Riñones', 6, true, NOW(), NOW()),
(135, 'Ultrasonido de Vejiga', 6, true, NOW(), NOW()),
(136, 'Ultrasonido Pélvico', 6, true, NOW(), NOW()),
(137, 'Ultrasonido Obstétrico', 6, true, NOW(), NOW()),
(138, 'Ultrasonido Transvaginal', 6, true, NOW(), NOW()),
(139, 'Ultrasonido de Próstata', 6, true, NOW(), NOW()),
(140, 'Ultrasonido de Tiroides', 6, true, NOW(), NOW()),
(141, 'Ultrasonido de Mamas', 6, true, NOW(), NOW()),
(142, 'Ultrasonido de Testículos', 6, true, NOW(), NOW()),
(143, 'Ultrasonido Doppler Venoso', 6, true, NOW(), NOW()),
(144, 'Ultrasonido Doppler Arterial', 6, true, NOW(), NOW()),
(145, 'Ultrasonido Doppler de Carótidas', 6, true, NOW(), NOW()),
(146, 'Ultrasonido Obstétrico con Doppler', 6, true, NOW(), NOW()),
(147, 'Ultrasonido de Partes Blandas', 6, true, NOW(), NOW()),
(148, 'Ultrasonido de Cuello', 6, true, NOW(), NOW()),
(149, 'Ultrasonido Doppler de Extremidades', 6, true, NOW(), NOW()),
(150, 'Ultrasonido de Abdomen Superior', 6, true, NOW(), NOW()),

-- TOMOGRAFÍA (7)
(151, 'Tomografía Axial Computarizada (TAC) de Cráneo', 7, true, NOW(), NOW()),
(152, 'TAC de Tórax', 7, true, NOW(), NOW()),
(153, 'TAC de Abdomen', 7, true, NOW(), NOW()),
(154, 'TAC de Pelvis', 7, true, NOW(), NOW()),
(155, 'TAC de Columna Cervical', 7, true, NOW(), NOW()),
(156, 'TAC de Columna Dorsal', 7, true, NOW(), NOW()),
(157, 'TAC de Columna Lumbar', 7, true, NOW(), NOW()),
(158, 'TAC de Cráneo con Contraste', 7, true, NOW(), NOW()),
(159, 'TAC de Tórax con Contraste', 7, true, NOW(), NOW()),
(160, 'TAC de Abdomen con Contraste', 7, true, NOW(), NOW()),
(161, 'TAC de Pelvis con Contraste', 7, true, NOW(), NOW()),
(162, 'TAC de Cuello', 7, true, NOW(), NOW()),
(163, 'TAC de Senos Paranasales', 7, true, NOW(), NOW()),
(164, 'TAC de Órbitas', 7, true, NOW(), NOW()),
(165, 'TAC de Huesos Faciales', 7, true, NOW(), NOW()),
(166, 'TAC de Extremidades', 7, true, NOW(), NOW()),
(167, 'Angio-TAC de Tórax', 7, true, NOW(), NOW()),
(168, 'Angio-TAC de Abdomen', 7, true, NOW(), NOW()),
(169, 'TAC de Tórax con Angiografía Pulmonar', 7, true, NOW(), NOW()),
(170, 'TAC Multicorte de Alta Resolución', 7, true, NOW(), NOW()),

-- RESONANCIA MAGNÉTICA (8)
(171, 'Resonancia Magnética de Cráneo', 8, true, NOW(), NOW()),
(172, 'Resonancia Magnética de Columna Cervical', 8, true, NOW(), NOW()),
(173, 'Resonancia Magnética de Columna Dorsal', 8, true, NOW(), NOW()),
(174, 'Resonancia Magnética de Columna Lumbar', 8, true, NOW(), NOW()),
(175, 'Resonancia Magnética de Rodilla', 8, true, NOW(), NOW()),
(176, 'Resonancia Magnética de Hombro', 8, true, NOW(), NOW()),
(177, 'Resonancia Magnética de Cadera', 8, true, NOW(), NOW()),
(178, 'Resonancia Magnética de Tobillo', 8, true, NOW(), NOW()),
(179, 'Resonancia Magnética de Muñeca', 8, true, NOW(), NOW()),
(180, 'Resonancia Magnética de Tórax', 8, true, NOW(), NOW()),
(181, 'Resonancia Magnética de Abdomen', 8, true, NOW(), NOW()),
(182, 'Resonancia Magnética de Pelvis', 8, true, NOW(), NOW()),
(183, 'Resonancia Magnética de Cráneo con Contraste', 8, true, NOW(), NOW()),
(184, 'Resonancia Magnética de Columna con Contraste', 8, true, NOW(), NOW()),
(185, 'Resonancia Magnética de Abdomen con Contraste', 8, true, NOW(), NOW()),
(186, 'Angioresonancia Magnética', 8, true, NOW(), NOW()),
(187, 'Resonancia Magnética de Mamas', 8, true, NOW(), NOW()),
(188, 'Resonancia Magnética de Próstata', 8, true, NOW(), NOW()),
(189, 'Resonancia Magnética Funcional', 8, true, NOW(), NOW()),
(190, 'Resonancia Magnética de Difusión', 8, true, NOW(), NOW()),

-- CARDIOLOGÍA (9)
(191, 'Electrocardiograma (ECG)', 9, true, NOW(), NOW()),
(192, 'Electrocardiograma de Esfuerzo', 9, true, NOW(), NOW()),
(193, 'Holter de 24 Horas', 9, true, NOW(), NOW()),
(194, 'Holter de 48 Horas', 9, true, NOW(), NOW()),
(195, 'Holter de 7 Días', 9, true, NOW(), NOW()),
(196, 'MAPA (Monitoreo Ambulatorio de Presión Arterial)', 9, true, NOW(), NOW()),
(197, 'Ecocardiograma Transtorácico', 9, true, NOW(), NOW()),
(198, 'Ecocardiograma Transesofágico', 9, true, NOW(), NOW()),
(199, 'Ecocardiograma de Esfuerzo', 9, true, NOW(), NOW()),
(200, 'Ecocardiograma con Doppler', 9, true, NOW(), NOW()),
(201, 'Prueba de Esfuerzo (Ergometría)', 9, true, NOW(), NOW()),
(202, 'Prueba de Esfuerzo con Medicina Nuclear', 9, true, NOW(), NOW()),
(203, 'Cateterismo Cardiaco', 9, true, NOW(), NOW()),
(204, 'Angiografía Coronaria', 9, true, NOW(), NOW()),
(205, 'Angiografía de Arterias Periféricas', 9, true, NOW(), NOW()),
(206, 'Prueba de Tilt (Mesa Basculante)', 9, true, NOW(), NOW()),
(207, 'Estudio Electrofisiológico', 9, true, NOW(), NOW()),
(208, 'Ablación por Radiofrecuencia', 9, true, NOW(), NOW()),
(209, 'Prueba de Tabla de Esfuerzo', 9, true, NOW(), NOW()),
(210, 'Ecocardiograma Fetal', 9, true, NOW(), NOW()),

-- GINECOLOGÍA (10)
(211, 'Papanicolaou (Citología Cervical)', 10, true, NOW(), NOW()),
(212, 'Colposcopía', 10, true, NOW(), NOW()),
(213, 'Biopsia de Cuello Uterino', 10, true, NOW(), NOW()),
(214, 'Ecografía Ginecológica', 10, true, NOW(), NOW()),
(215, 'Ecografía Obstétrica Primer Trimestre', 10, true, NOW(), NOW()),
(216, 'Ecografía Obstétrica Segundo Trimestre', 10, true, NOW(), NOW()),
(217, 'Ecografía Obstétrica Tercer Trimestre', 10, true, NOW(), NOW()),
(218, 'Ecografía de Morfología Fetal', 10, true, NOW(), NOW()),
(219, 'Ecografía Doppler Obstétrico', 10, true, NOW(), NOW()),
(220, 'Histerosalpingografía', 10, true, NOW(), NOW()),
(221, 'Histeroscopía Diagnóstica', 10, true, NOW(), NOW()),
(222, 'Laparoscopía Ginecológica', 10, true, NOW(), NOW()),
(223, 'Prueba de Hormonas Femeninas', 10, true, NOW(), NOW()),
(224, 'Prueba de Embarazo (Beta HCG)', 10, true, NOW(), NOW()),
(225, 'Prueba de Estrógenos', 10, true, NOW(), NOW()),
(226, 'Prueba de Progesterona', 10, true, NOW(), NOW()),
(227, 'Prueba de FSH', 10, true, NOW(), NOW()),
(228, 'Prueba de LH', 10, true, NOW(), NOW()),
(229, 'Prueba de Prolactina', 10, true, NOW(), NOW()),
(230, 'Mamografía', 10, true, NOW(), NOW()),

-- UROLOGÍA (11)
(231, 'Ecografía Urológica', 11, true, NOW(), NOW()),
(232, 'Ecografía de Próstata', 11, true, NOW(), NOW()),
(233, 'Ecografía de Testículos', 11, true, NOW(), NOW()),
(234, 'Ecografía de Vejiga', 11, true, NOW(), NOW()),
(235, 'Ecografía Renal', 11, true, NOW(), NOW()),
(236, 'Urografía Excretora', 11, true, NOW(), NOW()),
(237, 'Cistografía', 11, true, NOW(), NOW()),
(238, 'Cistoscopía', 11, true, NOW(), NOW()),
(239, 'Uretrocistografía', 11, true, NOW(), NOW()),
(240, 'Uretrocistoscopía', 11, true, NOW(), NOW()),
(241, 'Biopsia de Próstata', 11, true, NOW(), NOW()),
(242, 'Antígeno Prostático Específico (PSA)', 11, true, NOW(), NOW()),
(243, 'PSA Libre', 11, true, NOW(), NOW()),
(244, 'PSA Total', 11, true, NOW(), NOW()),
(245, 'Prueba de Testosterona', 11, true, NOW(), NOW()),
(246, 'Semenograma', 11, true, NOW(), NOW()),
(247, 'Análisis de Semen', 11, true, NOW(), NOW()),
(248, 'Prueba de Fertilidad Masculina', 11, true, NOW(), NOW()),
(249, 'Estudio Urodinámico', 11, true, NOW(), NOW()),
(250, 'Nefrostomía', 11, true, NOW(), NOW()),

-- GASTROENTEROLOGÍA (12)
(251, 'Endoscopía Digestiva Alta', 12, true, NOW(), NOW()),
(252, 'Colonoscopía', 12, true, NOW(), NOW()),
(253, 'Sigmoidoscopía', 12, true, NOW(), NOW()),
(254, 'Cápsula Endoscópica', 12, true, NOW(), NOW()),
(255, 'Colangiopancreatografía Retrógrada Endoscópica (CPRE)', 12, true, NOW(), NOW()),
(256, 'Ecografía Endoscópica', 12, true, NOW(), NOW()),
(257, 'Manometría Esofágica', 12, true, NOW(), NOW()),
(258, 'pHmetría Esofágica', 12, true, NOW(), NOW()),
(259, 'Prueba de Aliento para Helicobacter Pylori', 12, true, NOW(), NOW()),
(260, 'Prueba de Sangre Oculta en Heces', 12, true, NOW(), NOW()),
(261, 'Prueba de Antígeno Fecal', 12, true, NOW(), NOW()),
(262, 'Análisis de Heces', 12, true, NOW(), NOW()),
(263, 'Coprocultivo', 12, true, NOW(), NOW()),
(264, 'Prueba de Elastasa Fecal', 12, true, NOW(), NOW()),
(265, 'Prueba de Calprotectina Fecal', 12, true, NOW(), NOW()),
(266, 'Biopsia de Estómago', 12, true, NOW(), NOW()),
(267, 'Biopsia de Intestino', 12, true, NOW(), NOW()),
(268, 'Prueba de Tolerancia a la Lactosa', 12, true, NOW(), NOW()),
(269, 'Prueba de Malabsorción', 12, true, NOW(), NOW()),
(270, 'Endoscopía con Biopsia', 12, true, NOW(), NOW()),

-- ENDOCRINOLOGÍA (13)
(271, 'Perfil Tiroideo Completo', 13, true, NOW(), NOW()),
(272, 'TSH (Hormona Estimulante del Tiroides)', 13, true, NOW(), NOW()),
(273, 'T4 Libre', 13, true, NOW(), NOW()),
(274, 'T4 Total', 13, true, NOW(), NOW()),
(275, 'T3 Libre', 13, true, NOW(), NOW()),
(276, 'T3 Total', 13, true, NOW(), NOW()),
(277, 'Tiroglobulina', 13, true, NOW(), NOW()),
(278, 'Calcitonina', 13, true, NOW(), NOW()),
(279, 'Hormona del Crecimiento (GH)', 13, true, NOW(), NOW()),
(280, 'IGF-1 (Factor de Crecimiento Similar a la Insulina)', 13, true, NOW(), NOW()),
(281, 'Cortisol en Sangre', 13, true, NOW(), NOW()),
(282, 'Cortisol en Orina de 24 Horas', 13, true, NOW(), NOW()),
(283, 'ACTH (Hormona Adrenocorticotrópica)', 13, true, NOW(), NOW()),
(284, 'Aldosterona', 13, true, NOW(), NOW()),
(285, 'Renina', 13, true, NOW(), NOW()),
(286, 'Prueba de Tolerancia a la Glucosa', 13, true, NOW(), NOW()),
(287, 'Curva de Glucosa', 13, true, NOW(), NOW()),
(288, 'Insulina en Ayunas', 13, true, NOW(), NOW()),
(289, 'Peptido C', 13, true, NOW(), NOW()),
(290, 'Hemoglobina Glicosilada (HbA1c)', 13, true, NOW(), NOW()),

-- NEUROLOGÍA (14)
(291, 'Electroencefalograma (EEG)', 14, true, NOW(), NOW()),
(292, 'EEG con Privación de Sueño', 14, true, NOW(), NOW()),
(293, 'Electromiografía (EMG)', 14, true, NOW(), NOW()),
(294, 'Estudio de Conducción Nerviosa', 14, true, NOW(), NOW()),
(295, 'Potenciales Evocados Visuales', 14, true, NOW(), NOW()),
(296, 'Potenciales Evocados Auditivos', 14, true, NOW(), NOW()),
(297, 'Potenciales Evocados Somatosensoriales', 14, true, NOW(), NOW()),
(298, 'Resonancia Magnética de Cráneo', 14, true, NOW(), NOW()),
(299, 'Resonancia Magnética de Columna', 14, true, NOW(), NOW()),
(300, 'Angioresonancia de Cerebro', 14, true, NOW(), NOW()),
(301, 'TAC de Cráneo', 14, true, NOW(), NOW()),
(302, 'TAC de Columna', 14, true, NOW(), NOW()),
(303, 'Punción Lumbar', 14, true, NOW(), NOW()),
(304, 'Análisis de Líquido Cefalorraquídeo', 14, true, NOW(), NOW()),
(305, 'Doppler Transcraneal', 14, true, NOW(), NOW()),
(306, 'Doppler de Vasos del Cuello', 14, true, NOW(), NOW()),
(307, 'Polisomnografía', 14, true, NOW(), NOW()),
(308, 'Test de Latencia Múltiple del Sueño', 14, true, NOW(), NOW()),
(309, 'Biopsia de Nervio', 14, true, NOW(), NOW()),
(310, 'Biopsia de Músculo', 14, true, NOW(), NOW()),

-- OFTALMOLOGÍA (15)
(311, 'Examen de Agudeza Visual', 15, true, NOW(), NOW()),
(312, 'Refracción', 15, true, NOW(), NOW()),
(313, 'Tonometría (Presión Intraocular)', 15, true, NOW(), NOW()),
(314, 'Fondo de Ojo', 15, true, NOW(), NOW()),
(315, 'Oftalmoscopía', 15, true, NOW(), NOW()),
(316, 'Campimetría', 15, true, NOW(), NOW()),
(317, 'Perimetría', 15, true, NOW(), NOW()),
(318, 'Biomicroscopía', 15, true, NOW(), NOW()),
(319, 'Paquimetría', 15, true, NOW(), NOW()),
(320, 'Gonioscopía', 15, true, NOW(), NOW()),
(321, 'Ecografía Ocular', 15, true, NOW(), NOW()),
(322, 'Tomografía de Coherencia Óptica (OCT)', 15, true, NOW(), NOW()),
(323, 'Angiografía Fluoresceínica', 15, true, NOW(), NOW()),
(324, 'Angiografía con Verde de Indocianina', 15, true, NOW(), NOW()),
(325, 'Electroretinograma', 15, true, NOW(), NOW()),
(326, 'Potenciales Visuales Evocados', 15, true, NOW(), NOW()),
(327, 'Biopsia de Conjuntiva', 15, true, NOW(), NOW()),
(328, 'Prueba de Schirmer', 15, true, NOW(), NOW()),
(329, 'Prueba de Color', 15, true, NOW(), NOW()),
(330, 'Topografía Corneal', 15, true, NOW(), NOW()),

-- OTORRINOLARINGOLOGÍA (16)
(331, 'Audiometría', 16, true, NOW(), NOW()),
(332, 'Audiometría Tonal', 16, true, NOW(), NOW()),
(333, 'Audiometría Vocal', 16, true, NOW(), NOW()),
(334, 'Impedanciometría', 16, true, NOW(), NOW()),
(335, 'Timpanometría', 16, true, NOW(), NOW()),
(336, 'Reflejos Estapediales', 16, true, NOW(), NOW()),
(337, 'Potenciales Evocados Auditivos del Tronco Cerebral', 16, true, NOW(), NOW()),
(338, 'Otoemisiones Acústicas', 16, true, NOW(), NOW()),
(339, 'Rinoscopía', 16, true, NOW(), NOW()),
(340, 'Laringoscopía', 16, true, NOW(), NOW()),
(341, 'Laringoscopía Directa', 16, true, NOW(), NOW()),
(342, 'Videoendoscopía Nasofaríngea', 16, true, NOW(), NOW()),
(343, 'Rinomanometría', 16, true, NOW(), NOW()),
(344, 'Biopsia de Nasofaringe', 16, true, NOW(), NOW()),
(345, 'Biopsia de Laringe', 16, true, NOW(), NOW()),
(346, 'TAC de Huesos Temporales', 16, true, NOW(), NOW()),
(347, 'TAC de Senos Paranasales', 16, true, NOW(), NOW()),
(348, 'Resonancia Magnética de Oído Interno', 16, true, NOW(), NOW()),
(349, 'Prueba Vestibular', 16, true, NOW(), NOW()),
(350, 'Videonistagmografía', 16, true, NOW(), NOW()),

-- DERMATOLOGÍA (17)
(351, 'Biopsia de Piel', 17, true, NOW(), NOW()),
(352, 'Dermoscopía', 17, true, NOW(), NOW()),
(353, 'Dermatoscopía Digital', 17, true, NOW(), NOW()),
(354, 'Prueba del Parche', 17, true, NOW(), NOW()),
(355, 'Prueba de Prick', 17, true, NOW(), NOW()),
(356, 'Prueba Intradérmica', 17, true, NOW(), NOW()),
(357, 'Cultivo de Hongos', 17, true, NOW(), NOW()),
(358, 'Examen Directo de Hongos', 17, true, NOW(), NOW()),
(359, 'Prueba de Woods', 17, true, NOW(), NOW()),
(360, 'Biopsia de Cuero Cabelludo', 17, true, NOW(), NOW()),
(361, 'Análisis de Cabello', 17, true, NOW(), NOW()),
(362, 'Prueba de Alergia Cutánea', 17, true, NOW(), NOW()),
(363, 'Prueba de Fototipo', 17, true, NOW(), NOW()),
(364, 'Prueba de Sensibilidad', 17, true, NOW(), NOW()),
(365, 'Cultivo de Bacterias Cutáneas', 17, true, NOW(), NOW()),
(366, 'Análisis de Uñas', 17, true, NOW(), NOW()),
(367, 'Prueba de Acidez', 17, true, NOW(), NOW()),
(368, 'Prueba de Hidratación', 17, true, NOW(), NOW()),
(369, 'Mapeo de Lunares', 17, true, NOW(), NOW()),
(370, 'Dermatoscopía de Seguimiento', 17, true, NOW(), NOW()),

-- PATOLOGÍA (18)
(371, 'Biopsia por Aspiración con Aguja Fina (BAAF)', 18, true, NOW(), NOW()),
(372, 'Biopsia Core', 18, true, NOW(), NOW()),
(373, 'Biopsia Quirúrgica', 18, true, NOW(), NOW()),
(374, 'Biopsia de Médula Ósea', 18, true, NOW(), NOW()),
(375, 'Citología de Exudado', 18, true, NOW(), NOW()),
(376, 'Citología de Líquidos', 18, true, NOW(), NOW()),
(377, 'Análisis Histopatológico', 18, true, NOW(), NOW()),
(378, 'Inmunohistoquímica', 18, true, NOW(), NOW()),
(379, 'Análisis de Fluorescencia In Situ (FISH)', 18, true, NOW(), NOW()),
(380, 'Análisis Molecular', 18, true, NOW(), NOW()),
(381, 'Biopsia de Ganglio Linfático', 18, true, NOW(), NOW()),
(382, 'Citología de Tiroides', 18, true, NOW(), NOW()),
(383, 'Citología de Mama', 18, true, NOW(), NOW()),
(384, 'Citología de Pulmón', 18, true, NOW(), NOW()),
(385, 'Citología de Hígado', 18, true, NOW(), NOW()),
(386, 'Citología de Páncreas', 18, true, NOW(), NOW()),
(387, 'Biopsia de Próstata', 18, true, NOW(), NOW()),
(388, 'Biopsia de Riñón', 18, true, NOW(), NOW()),
(389, 'Biopsia de Hígado', 18, true, NOW(), NOW()),
(390, 'Biopsia de Pulmón', 18, true, NOW(), NOW()),

-- GENÉTICA (19)
(391, 'Cariotipo', 19, true, NOW(), NOW()),
(392, 'Análisis Cromosómico', 19, true, NOW(), NOW()),
(393, 'Prueba de ADN', 19, true, NOW(), NOW()),
(394, 'Prueba de Paternidad', 19, true, NOW(), NOW()),
(395, 'Análisis Genético de Portadores', 19, true, NOW(), NOW()),
(396, 'Prueba Prenatal No Invasiva', 19, true, NOW(), NOW()),
(397, 'Amniocentesis', 19, true, NOW(), NOW()),
(398, 'Biopsia de Vellosidades Coriónicas', 19, true, NOW(), NOW()),
(399, 'Secuenciación Genómica', 19, true, NOW(), NOW()),
(400, 'Análisis de Mutaciones', 19, true, NOW(), NOW()),
(401, 'Prueba de Síndrome de Down', 19, true, NOW(), NOW()),
(402, 'Prueba de Fibrosis Quística', 19, true, NOW(), NOW()),
(403, 'Prueba de Talasemia', 19, true, NOW(), NOW()),
(404, 'Prueba de Hemofilia', 19, true, NOW(), NOW()),
(405, 'Prueba de Enfermedad de Huntington', 19, true, NOW(), NOW()),
(406, 'Análisis de Farmacogenómica', 19, true, NOW(), NOW()),
(407, 'Prueba de Cáncer Hereditario', 19, true, NOW(), NOW()),
(408, 'Prueba de BRCA', 19, true, NOW(), NOW()),
(409, 'Análisis de Microarrays', 19, true, NOW(), NOW()),
(410, 'Prueba de Predisposición Genética', 19, true, NOW(), NOW()),

-- MEDICINA NUCLEAR (20)
(411, 'Gammagrafía Ósea', 20, true, NOW(), NOW()),
(412, 'Gammagrafía Tiroidea', 20, true, NOW(), NOW()),
(413, 'Gammagrafía Renal', 20, true, NOW(), NOW()),
(414, 'Gammagrafía Hepática', 20, true, NOW(), NOW()),
(415, 'Gammagrafía Pulmonar', 20, true, NOW(), NOW()),
(416, 'Gammagrafía Cardiaca', 20, true, NOW(), NOW()),
(417, 'Gammagrafía de Perfusión Miocárdica', 20, true, NOW(), NOW()),
(418, 'PET Scan (Tomografía por Emisión de Positrones)', 20, true, NOW(), NOW()),
(419, 'PET-CT', 20, true, NOW(), NOW()),
(420, 'SPECT (Tomografía Computarizada por Emisión de Fotón Único)', 20, true, NOW(), NOW()),
(421, 'SPECT Cerebral', 20, true, NOW(), NOW()),
(422, 'Gammagrafía de Paratiroides', 20, true, NOW(), NOW()),
(423, 'Gammagrafía de Adrenales', 20, true, NOW(), NOW()),
(424, 'Gammagrafía de Linfáticos', 20, true, NOW(), NOW()),
(425, 'Gammagrafía de Glándulas Salivales', 20, true, NOW(), NOW()),
(426, 'Prueba de Captación de Yodo', 20, true, NOW(), NOW()),
(427, 'Gammagrafía de Medula Ósea', 20, true, NOW(), NOW()),
(428, 'Gammagrafía de Inflamación', 20, true, NOW(), NOW()),
(429, 'Gammagrafía de Abscesos', 20, true, NOW(), NOW()),
(430, 'Gammagrafía de Tumores', 20, true, NOW(), NOW()),

-- ESPIROMETRÍA (21)
(431, 'Espirometría Simple', 21, true, NOW(), NOW()),
(432, 'Espirometría Completa', 21, true, NOW(), NOW()),
(433, 'Espirometría con Prueba de Broncodilatación', 21, true, NOW(), NOW()),
(434, 'Volúmenes Pulmonares', 21, true, NOW(), NOW()),
(435, 'Capacidad de Difusión de Monóxido de Carbono (DLCO)', 21, true, NOW(), NOW()),
(436, 'Prueba de Esfuerzo Respiratorio', 21, true, NOW(), NOW()),
(437, 'Prueba de Oxígeno', 21, true, NOW(), NOW()),
(438, 'Gasometría Arterial', 21, true, NOW(), NOW()),
(439, 'Gasometría Venosa', 21, true, NOW(), NOW()),
(440, 'Prueba de Caminata de 6 Minutos', 21, true, NOW(), NOW()),
(441, 'Prueba de Ejercicio Cardiopulmonar', 21, true, NOW(), NOW()),
(442, 'Pletismografía', 21, true, NOW(), NOW()),
(443, 'Prueba de Reactividad Bronquial', 21, true, NOW(), NOW()),
(444, 'Prueba de Reto con Metacolina', 21, true, NOW(), NOW()),
(445, 'Prueba de Reto con Histamina', 21, true, NOW(), NOW()),
(446, 'Prueba de Flujo Espiratorio Pico', 21, true, NOW(), NOW()),
(447, 'Prueba de Capacidad Pulmonar', 21, true, NOW(), NOW()),
(448, 'Prueba de Volúmenes Residuales', 21, true, NOW(), NOW()),
(449, 'Prueba de Capacidad Vital', 21, true, NOW(), NOW()),
(450, 'Prueba de Ventilación Máxima', 21, true, NOW(), NOW()),

-- ELECTROCARDIOGRAMA (22)
(451, 'Electrocardiograma de Reposo', 22, true, NOW(), NOW()),
(452, 'Electrocardiograma de Esfuerzo', 22, true, NOW(), NOW()),
(453, 'Electrocardiograma de 12 Derivaciones', 22, true, NOW(), NOW()),
(454, 'Electrocardiograma de Monitoreo Continuo', 22, true, NOW(), NOW()),
(455, 'Electrocardiograma de Alta Resolución', 22, true, NOW(), NOW()),
(456, 'Electrocardiograma de Señal Promediada', 22, true, NOW(), NOW()),
(457, 'Electrocardiograma de Vectocardiografía', 22, true, NOW(), NOW()),
(458, 'Electrocardiograma de Intervalos', 22, true, NOW(), NOW()),
(459, 'Electrocardiograma de Onda T', 22, true, NOW(), NOW()),
(460, 'Electrocardiograma de Análisis de Variabilidad', 22, true, NOW(), NOW()),
(461, 'Electrocardiograma de Ritmo', 22, true, NOW(), NOW()),
(462, 'Electrocardiograma de Frecuencia Cardiaca', 22, true, NOW(), NOW()),
(463, 'Electrocardiograma de Segmento ST', 22, true, NOW(), NOW()),
(464, 'Electrocardiograma de Complejo QRS', 22, true, NOW(), NOW()),
(465, 'Electrocardiograma de Onda P', 22, true, NOW(), NOW()),
(466, 'Electrocardiograma de Derivaciones Precordiales', 22, true, NOW(), NOW()),
(467, 'Electrocardiograma de Derivaciones de Extremidades', 22, true, NOW(), NOW()),
(468, 'Electrocardiograma de Monitoreo Ambulatorio', 22, true, NOW(), NOW()),
(469, 'Electrocardiograma de Telemetría', 22, true, NOW(), NOW()),
(470, 'Electrocardiograma de Análisis Avanzado', 22, true, NOW(), NOW()),

-- MEDICINA DEL DEPORTE (23)
(471, 'Prueba de Esfuerzo Máximo', 23, true, NOW(), NOW()),
(472, 'Prueba de Consumo de Oxígeno (VO2 Max)', 23, true, NOW(), NOW()),
(473, 'Prueba de Umbral Anaeróbico', 23, true, NOW(), NOW()),
(474, 'Prueba de Composición Corporal', 23, true, NOW(), NOW()),
(475, 'Análisis de Impedancia Bioeléctrica', 23, true, NOW(), NOW()),
(476, 'Prueba de Densidad Ósea', 23, true, NOW(), NOW()),
(477, 'Prueba de Flexibilidad', 23, true, NOW(), NOW()),
(478, 'Prueba de Fuerza Muscular', 23, true, NOW(), NOW()),
(479, 'Prueba de Resistencia', 23, true, NOW(), NOW()),
(480, 'Prueba de Agilidad', 23, true, NOW(), NOW()),
(481, 'Prueba de Velocidad', 23, true, NOW(), NOW()),
(482, 'Prueba de Coordinación', 23, true, NOW(), NOW()),
(483, 'Prueba de Equilibrio', 23, true, NOW(), NOW()),
(484, 'Prueba de Reacción', 23, true, NOW(), NOW()),
(485, 'Prueba de Capacidad Aeróbica', 23, true, NOW(), NOW()),
(486, 'Prueba de Capacidad Anaeróbica', 23, true, NOW(), NOW()),
(487, 'Prueba de Recuperación', 23, true, NOW(), NOW()),
(488, 'Prueba de Hidratación', 23, true, NOW(), NOW()),
(489, 'Prueba de Nutrición Deportiva', 23, true, NOW(), NOW()),
(490, 'Prueba de Rendimiento Deportivo', 23, true, NOW(), NOW()),

-- ONCOLOGÍA (24)
(491, 'Mamografía de Detección', 24, true, NOW(), NOW()),
(492, 'Mamografía Diagnóstica', 24, true, NOW(), NOW()),
(493, 'Tomografía de Mama', 24, true, NOW(), NOW()),
(494, 'Resonancia Magnética de Mama', 24, true, NOW(), NOW()),
(495, 'Biopsia de Mama', 24, true, NOW(), NOW()),
(496, 'Marcadores Tumorales', 24, true, NOW(), NOW()),
(497, 'CEA (Antígeno Carcinoembrionario)', 24, true, NOW(), NOW()),
(498, 'CA 19-9', 24, true, NOW(), NOW()),
(499, 'CA 125', 24, true, NOW(), NOW()),
(500, 'PSA (Antígeno Prostático Específico)', 24, true, NOW(), NOW())

ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    category_id = EXCLUDED.category_id,
    is_active = EXCLUDED.is_active;

