-- INSERT statements for medications
-- Generated on 2025-10-22 20:00:44.419344

INSERT INTO medications (id, name, created_at, updated_at) VALUES ('1', 'Paracetamol', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('2', 'Ibuprofeno', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('3', 'Amoxicilina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('4', 'Omeprazol', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('5', 'Metformina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('6', 'Losartán', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('7', 'Atorvastatina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('8', 'Levotiroxina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('9', 'Amlodipino', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('10', 'Salbutamol', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('11', 'Ciprofloxacino', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('12', 'Diclofenaco', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('13', 'Ranitidina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('14', 'Loratadina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('15', 'Cetirizina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('16', 'Azitromicina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('17', 'Clonazepam', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('18', 'Alprazolam', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('19', 'Fluoxetina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('20', 'Sertralina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('21', 'Gabapentina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('22', 'Pregabalina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('23', 'Tramadol', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('24', 'Ketorolaco', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('25', 'Naproxeno', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('26', 'Captopril', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('27', 'Enalapril', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('28', 'Metoprolol', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('29', 'Carvedilol', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('30', 'Furosemida', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('31', 'Hidroclorotiazida', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('32', 'Espironolactona', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('33', 'Warfarina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('34', 'Rivaroxabán', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('35', 'Apixabán', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('36', 'Clopidogrel', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('37', 'Aspirina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('38', 'Simvastatina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('39', 'Rosuvastatina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('40', 'Fenofibrato', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('41', 'Glibenclamida', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('42', 'Glimepirida', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('43', 'Sitagliptina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('44', 'Linagliptina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('45', 'Insulina NPH', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('46', 'Insulina Glargina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('47', 'Insulina Lispro', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('48', 'Insulina Aspart', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('49', 'Prednisona', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('50', 'Dexametasona', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('51', 'Hidrocortisona', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('52', 'Budesonida', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('53', 'Beclometasona', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('54', 'Fluticasona', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('55', 'Montelukast', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('56', 'Teofilina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('57', 'Bromuro de Ipratropio', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('58', 'Formoterol', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('59', 'Salmeterol', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('60', 'Tiotropio', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('61', 'Digoxina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('62', 'Bisoprolol', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('63', 'Nebivolol', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('64', 'Diltiazem', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('65', 'Verapamilo', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('66', 'Nitroglicerina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('67', 'Isosorbida', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('68', 'Nifedipino', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('69', 'Felodipino', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('70', 'Ivabradina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('71', 'Sacubitrilo/Valsartán', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('72', 'Doxazosina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('73', 'Terazosina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('74', 'Tamsulosina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('75', 'Finasterida', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('76', 'Dutasterida', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('77', 'Sildenafil', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('78', 'Tadalafil', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('79', 'Vardenafil', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('80', 'Levodopa/Carbidopa', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('81', 'Pramipexol', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('82', 'Ropinirol', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('83', 'Selegilina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('84', 'Rasagilina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('85', 'Entacapona', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('86', 'Rivastigmina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('87', 'Donepezilo', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('88', 'Memantina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('89', 'Quetiapina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('90', 'Olanzapina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('91', 'Risperidona', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('92', 'Aripiprazol', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('93', 'Haloperidol', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('94', 'Clorpromazina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('95', 'Litio', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('96', 'Ácido Valproico', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('97', 'Carbamazepina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('98', 'Lamotrigina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('99', 'Topiramato', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('100', 'Levetiracetam', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('101', 'Fenitoína', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('102', 'Fenobarbital', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('103', 'Oxcarbazepina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('104', 'Zonisamida', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('105', 'Perampanel', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('106', 'Duloxetina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('107', 'Venlafaxina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('108', 'Escitalopram', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('109', 'Paroxetina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('110', 'Citalopram', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('111', 'Amitriptilina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('112', 'Nortriptilina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('113', 'Imipramina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('114', 'Clomipramina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('115', 'Mirtazapina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('116', 'Trazodona', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('117', 'Bupropión', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('118', 'Metilfenidato', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('119', 'Atomoxetina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('120', 'Lisdexanfetamina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('121', 'Modafinilo', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('122', 'Armodafinilo', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('123', 'Zolpidem', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('124', 'Eszopiclona', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('125', 'Zopiclona', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('126', 'Melatonina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('128', 'Doxepina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('129', 'Hidroxizina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('130', 'Prometazina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('131', 'Dimenhidrinato', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('132', 'Metoclopramida', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('133', 'Domperidona', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('134', 'Ondansetrón', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('135', 'Granisetrón', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('136', 'Loperamida', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('137', 'Bisacodilo', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('138', 'Lactulosa', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('139', 'Polietilenglicol', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('140', 'Mesalazina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('141', 'Sulfasalazina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('142', 'Azatioprina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('143', 'Mercaptopurina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('144', 'Metotrexato', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('145', 'Ciclofosfamida', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('146', 'Ciclosporina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('147', 'Tacrolimus', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('148', 'Micofenolato', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('149', 'Rituximab', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('150', 'Adalimumab', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('151', 'Infliximab', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('152', 'Etanercept', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('153', 'Golimumab', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('154', 'Certolizumab', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('155', 'Tocilizumab', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('156', 'Alopurinol', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('157', 'Colchicina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('158', 'Febuxostat', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('159', 'Probenecid', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('160', 'Hidroxicloroquina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('161', 'Cloroquina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('163', 'Leflunomida', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('165', 'Celecoxib', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('166', 'Etoricoxib', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('167', 'Meloxicam', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('168', 'Piroxicam', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('169', 'Indometacina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('170', 'Ketoprofeno', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('171', 'Clindamicina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('172', 'Eritromicina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('173', 'Claritromicina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('174', 'Doxiciclina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('175', 'Tetraciclina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('176', 'Trimetoprima/Sulfametoxazol', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('177', 'Nitrofurantoína', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('178', 'Fosfomicina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('179', 'Ceftriaxona', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('180', 'Cefotaxima', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('181', 'Cefuroxima', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('182', 'Cefalexina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('183', 'Cefixima', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('184', 'Cefepima', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('185', 'Meropenem', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('186', 'Imipenem', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('187', 'Ertapenem', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('188', 'Piperacilina/Tazobactam', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('189', 'Ampicilina/Sulbactam', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('190', 'Amoxicilina/Clavulanato', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('191', 'Vancomicina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('192', 'Linezolid', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('193', 'Daptomicina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('194', 'Teicoplanina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('195', 'Metronidazol', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('196', 'Fluconazol', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('197', 'Itraconazol', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('198', 'Voriconazol', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('199', 'Anfotericina B', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('200', 'Nistatina', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('201', 'Aciclovir', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('202', 'Valaciclovir', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('203', 'Famciclovir', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('204', 'Ganciclovir', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('205', 'Oseltamivir', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('206', 'Zanamivir', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('207', 'Lopinavir/Ritonavir', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('208', 'Darunavir', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('209', 'Atazanavir', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('210', 'Raltegravir', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('211', 'Amoxicilina + Ácido Clavulánico', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('212', 'Azitromicina 500mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('213', 'Claritromicina 500mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('214', 'Cefalexina 500mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('215', 'Ceftriaxona 1g', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('216', 'Ciprofloxacino 500mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('217', 'Levofloxacino 750mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('218', 'Moxifloxacino 400mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('219', 'Nitrofurantoína 100mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('220', 'Trimetoprima + Sulfametoxazol', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('221', 'Doxiciclina 100mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('222', 'Metronidazol 500mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('223', 'Clindamicina 300mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('224', 'Eritromicina 500mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('225', 'Vancomicina 500mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('226', 'Gentamicina 80mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('227', 'Cefotaxima 1g', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('228', 'Cefuroxima 500mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('229', 'Ampicilina 500mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('230', 'Piperacilina + Tazobactam', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('231', 'Meropenem 1g', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('232', 'Imipenem 500mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('233', 'Linezolid 600mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('234', 'Tetraciclina 500mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('235', 'Minociclina 100mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('236', 'Rifampicina 300mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('237', 'Isoniazida 300mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('238', 'Etambutol 400mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('239', 'Pirazinamida 500mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('240', 'Estreptomicina 1g', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('241', 'Paracetamol 1g', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('242', 'Ibuprofeno 400mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('243', 'Ibuprofeno 600mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('244', 'Naproxeno 500mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('245', 'Naproxeno Sódico 550mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('246', 'Diclofenaco 50mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('247', 'Diclofenaco 75mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('248', 'Ketorolaco 10mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('249', 'Ketorolaco 30mg inyectable', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('250', 'Meloxicam 15mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('251', 'Celecoxib 200mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('252', 'Etoricoxib 90mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('253', 'Piroxicam 20mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('254', 'Indometacina 25mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('255', 'Metamizol 500mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('256', 'Tramadol 50mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('257', 'Tramadol + Paracetamol', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('258', 'Codeína + Paracetamol', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('259', 'Morfina 10mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('260', 'Oxicodona 5mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('261', 'Fentanilo parche 25mcg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('262', 'Buprenorfina 0.2mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('263', 'Aspirina 100mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('264', 'Aspirina 500mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('265', 'Paracetamol + Cafeína', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('266', 'Enalapril 10mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('267', 'Enalapril 20mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('268', 'Losartán 50mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('269', 'Losartán 100mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('270', 'Valsartán 80mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('271', 'Valsartán 160mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('272', 'Telmisartán 40mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('273', 'Telmisartán 80mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('274', 'Irbesartán 150mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('275', 'Candesartán 16mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('276', 'Captopril 25mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('277', 'Ramipril 5mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('278', 'Amlodipino 5mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('279', 'Amlodipino 10mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('280', 'Nifedipino 30mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('281', 'Diltiazem 60mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('282', 'Verapamilo 80mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('283', 'Atenolol 50mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('284', 'Metoprolol 50mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('285', 'Metoprolol 100mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('286', 'Bisoprolol 5mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('287', 'Carvedilol 25mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('288', 'Propranolol 40mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('289', 'Nebivolol 5mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('290', 'Hidroclorotiazida 25mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('291', 'Furosemida 40mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('292', 'Espironolactona 25mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('293', 'Espironolactona 100mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('294', 'Clortalidona 25mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('295', 'Digoxina 0.25mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('296', 'Isosorbide 10mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('297', 'Nitroglicerina sublingual', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('298', 'Clopidogrel 75mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('299', 'Warfarina 5mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('300', 'Rivaroxabán 20mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('301', 'Metformina 500mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('302', 'Metformina 850mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('303', 'Metformina 1000mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('304', 'Glibenclamida 5mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('305', 'Glimepirida 2mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('306', 'Glimepirida 4mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('307', 'Glipizida 5mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('308', 'Sitagliptina 100mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('309', 'Vildagliptina 50mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('310', 'Linagliptina 5mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('311', 'Saxagliptina 5mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('312', 'Empagliflozina 10mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('313', 'Dapagliflozina 10mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('314', 'Canagliflozina 100mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('315', 'Pioglitazona 30mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('316', 'Acarbosa 100mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('318', 'Insulina Rápida', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('321', 'Omeprazol 20mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('322', 'Omeprazol 40mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('323', 'Esomeprazol 40mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('324', 'Pantoprazol 40mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('325', 'Lansoprazol 30mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('326', 'Ranitidina 150mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('327', 'Famotidina 40mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('328', 'Hidróxido de Aluminio + Magnesio', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('329', 'Sucralfato 1g', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('330', 'Bismuto Subsalicilato', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('331', 'Domperidona 10mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('332', 'Metoclopramida 10mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('333', 'Ondansetrón 8mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('334', 'Loperamida 2mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('335', 'Butilhioscina 10mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('336', 'Trimebutina 200mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('337', 'Simeticona 80mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('339', 'Bisacodilo 5mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('340', 'Senósidos 8.6mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('341', 'Mesalazina 500mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('342', 'Sulfasalazina 500mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('343', 'Prucaloprida 2mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('344', 'Rifaximina 550mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('345', 'Ácido Ursodesoxicólico 300mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('346', 'Salbutamol inhalador', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('347', 'Salbutamol jarabe', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('348', 'Salmeterol inhalador', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('349', 'Formoterol inhalador', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('350', 'Budesonida inhalador', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('351', 'Fluticasona inhalador', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('352', 'Beclometasona inhalador', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('353', 'Montelukast 10mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('354', 'Montelukast 4mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('355', 'Teofilina 200mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('356', 'Bromhexina 8mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('357', 'Ambroxol 30mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('358', 'Ambroxol jarabe', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('359', 'Acetilcisteína 600mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('360', 'Dextrometorfano', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('361', 'Codeína jarabe', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('362', 'Loratadina 10mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('363', 'Cetirizina 10mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('364', 'Fexofenadina 120mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('365', 'Desloratadina 5mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('366', 'Fluoxetina 20mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('367', 'Sertralina 50mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('368', 'Sertralina 100mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('369', 'Paroxetina 20mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('370', 'Citalopram 20mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('371', 'Escitalopram 10mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('372', 'Venlafaxina 75mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('373', 'Duloxetina 60mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('374', 'Amitriptilina 25mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('375', 'Nortriptilina 25mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('376', 'Clonazepam 0.5mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('377', 'Clonazepam 2mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('378', 'Alprazolam 0.25mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('379', 'Alprazolam 0.5mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('380', 'Lorazepam 1mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('381', 'Diazepam 5mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('382', 'Diazepam 10mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('383', 'Zolpidem 10mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('384', 'Quetiapina 25mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('385', 'Quetiapina 100mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('386', 'Olanzapina 10mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('387', 'Risperidona 2mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('388', 'Haloperidol 5mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('389', 'Ácido Valproico 500mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('390', 'Carbamazepina 200mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('391', 'Fenitoína 100mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('392', 'Levetiracetam 500mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('393', 'Gabapentina 300mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('394', 'Pregabalina 75mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('395', 'Topiramato 100mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('396', 'Levotiroxina 50mcg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('397', 'Levotiroxina 100mcg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('398', 'Levotiroxina 125mcg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('399', 'Metimazol 5mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('400', 'Propiltiouracilo 50mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('401', 'Prednisona 5mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('402', 'Prednisona 50mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('403', 'Dexametasona 4mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('404', 'Hidrocortisona 100mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('405', 'Estrógenos conjugados', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('406', 'Estradiol 1mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('407', 'Progesterona 200mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('408', 'Noretisterona 5mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('409', 'Testosterona gel', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('410', 'Cabergolina 0.5mg', NULL, NULL);
INSERT INTO medications (id, name, created_at, updated_at) VALUES ('411', 'este es', '2025-10-22 23:08:11.959643', '2025-10-22 23:08:11.959648');

-- End of medications data

