# Cloud Build configuration for automatic backend deployment
# Triggered on push to main branch

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/cortex-repo/backend:${SHORT_SHA}'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/cortex-repo/backend:latest'
      - '.'
    dir: 'backend'

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/cortex-repo/backend:${SHORT_SHA}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/cortex-repo/backend:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cortex-backend'
      - '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/cortex-repo/backend:${SHORT_SHA}'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=20'
      - '--concurrency=20'
      - '--timeout=120'

      - '--add-cloudsql-instances=${PROJECT_ID}:us-central1:cortex-db-prod'
      - '--set-env-vars=APP_ENV=production,DATABASE_URL=${_DATABASE_URL},GCP_PROJECT_ID=${PROJECT_ID},GCP_REGION=us-central1,GCP_STORAGE_BUCKET=cortex-medical-records-prod,SECRET_KEY=${_SECRET_KEY},JWT_SECRET_KEY=${_JWT_SECRET_KEY},MEDICAL_ENCRYPTION_KEY=${_MEDICAL_ENCRYPTION_KEY},ENABLE_ENCRYPTION=true,META_WHATSAPP_TOKEN=${_META_WHATSAPP_TOKEN},META_WHATSAPP_VERIFY_TOKEN=${_META_WHATSAPP_VERIFY_TOKEN},META_WHATSAPP_APP_SECRET=${_META_WHATSAPP_APP_SECRET},META_WHATSAPP_PHONE_ID=${_META_WHATSAPP_PHONE_ID},GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET},GEMINI_MODEL=gemini-1.5-flash,GEMINI_BOT_ENABLED=true,GEMINI_MAX_APPOINTMENT_DAYS=90,GEMINI_CONVERSATION_TIMEOUT_MINUTES=30,GEMINI_MAX_CONTEXT_MESSAGES=15,GEMINI_ENABLE_CACHE=true,GEMINI_CACHE_TTL_SECONDS=300,GEMINI_RATE_LIMIT_PER_USER=1,GEMINI_RATE_LIMIT_MESSAGES_PER_MINUTE=10,GEMINI_COST_ALERT_THRESHOLD=100000,GEMINI_MAX_RETRIES=2,GEMINI_FALLBACK_ENABLED=true,WHATSAPP_CONVERSATION_WINDOW_HOURS=24,WHATSAPP_ENABLE_COST_TRACKING=true,WHATSAPP_ALERT_ON_EXPIRED_CONVERSATIONS=true,CORS_ORIGINS=*,LOG_LEVEL=info'

# Build timeout (10 minutes)
timeout: 600s

# Substitutions (can be overridden)
substitutions:
  _REGION: us-central1

# Images to be pushed to Artifact Registry
images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/cortex-repo/backend:${SHORT_SHA}'
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/cortex-repo/backend:latest'

# Options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
