-- ============================================================================
-- SCRIPT DE SETUP INICIAL - PARTE 2
-- Medicamentos y Diagnósticos
-- ============================================================================

-- ============================================================================
-- 5. MEDICAMENTOS (403 medicamentos)
-- ============================================================================
\echo '💊 Insertando medicamentos...'

INSERT INTO medications (name) VALUES
-- Medicamentos comunes existentes (primeros 207)
('Paracetamol'),
('Ibuprofeno'),
('Amoxicilina'),
('Omeprazol'),
('Losartán'),
('Metformina'),
('Atorvastatina'),
('Salbutamol'),
('Clonazepam'),
('Diazepam'),

-- ANTIBIÓTICOS ADICIONALES
('Amoxicilina + Ácido Clavulánico'),
('Azitromicina 500mg'),
('Claritromicina 500mg'),
('Cefalexina 500mg'),
('Ceftriaxona 1g'),
('Ciprofloxacino 500mg'),
('Levofloxacino 750mg'),
('Moxifloxacino 400mg'),
('Nitrofurantoína 100mg'),
('Trimetoprima + Sulfametoxazol'),
('Doxiciclina 100mg'),
('Metronidazol 500mg'),
('Clindamicina 300mg'),
('Eritromicina 500mg'),
('Vancomicina 500mg'),
('Gentamicina 80mg'),
('Cefotaxima 1g'),
('Cefuroxima 500mg'),
('Ampicilina 500mg'),
('Piperacilina + Tazobactam'),
('Meropenem 1g'),
('Imipenem 500mg'),
('Linezolid 600mg'),
('Tetraciclina 500mg'),
('Minociclina 100mg'),
('Rifampicina 300mg'),
('Isoniazida 300mg'),
('Etambutol 400mg'),
('Pirazinamida 500mg'),
('Estreptomicina 1g'),

-- ANALGÉSICOS Y ANTIINFLAMATORIOS
('Paracetamol 1g'),
('Ibuprofeno 400mg'),
('Ibuprofeno 600mg'),
('Naproxeno 500mg'),
('Naproxeno Sódico 550mg'),
('Diclofenaco 50mg'),
('Diclofenaco 75mg'),
('Ketorolaco 10mg'),
('Ketorolaco 30mg inyectable'),
('Meloxicam 15mg'),
('Celecoxib 200mg'),
('Etoricoxib 90mg'),
('Piroxicam 20mg'),
('Indometacina 25mg'),
('Metamizol 500mg'),
('Tramadol 50mg'),
('Tramadol + Paracetamol'),
('Codeína + Paracetamol'),
('Morfina 10mg'),
('Oxicodona 5mg'),
('Fentanilo parche 25mcg'),
('Buprenorfina 0.2mg'),
('Aspirina 100mg'),
('Aspirina 500mg'),
('Paracetamol + Cafeína'),

-- CARDIOVASCULARES
('Enalapril 10mg'),
('Enalapril 20mg'),
('Losartán 50mg'),
('Losartán 100mg'),
('Valsartán 80mg'),
('Valsartán 160mg'),
('Telmisartán 40mg'),
('Telmisartán 80mg'),
('Irbesartán 150mg'),
('Candesartán 16mg'),
('Captopril 25mg'),
('Ramipril 5mg'),
('Amlodipino 5mg'),
('Amlodipino 10mg'),
('Nifedipino 30mg'),
('Diltiazem 60mg'),
('Verapamilo 80mg'),
('Atenolol 50mg'),
('Metoprolol 50mg'),
('Metoprolol 100mg'),
('Bisoprolol 5mg'),
('Carvedilol 25mg'),
('Propranolol 40mg'),
('Nebivolol 5mg'),
('Hidroclorotiazida 25mg'),
('Furosemida 40mg'),
('Espironolactona 25mg'),
('Espironolactona 100mg'),
('Clortalidona 25mg'),
('Digoxina 0.25mg'),
('Isosorbide 10mg'),
('Nitroglicerina sublingual'),
('Clopidogrel 75mg'),
('Warfarina 5mg'),
('Rivaroxabán 20mg'),

-- ANTIDIABÉTICOS
('Metformina 500mg'),
('Metformina 850mg'),
('Metformina 1000mg'),
('Glibenclamida 5mg'),
('Glimepirida 2mg'),
('Glimepirida 4mg'),
('Glipizida 5mg'),
('Sitagliptina 100mg'),
('Vildagliptina 50mg'),
('Linagliptina 5mg'),
('Saxagliptina 5mg'),
('Empagliflozina 10mg'),
('Dapagliflozina 10mg'),
('Canagliflozina 100mg'),
('Pioglitazona 30mg'),
('Acarbosa 100mg'),
('Insulina NPH'),
('Insulina Rápida'),
('Insulina Glargina'),
('Insulina Lispro'),

-- GASTROINTESTINALES
('Omeprazol 20mg'),
('Omeprazol 40mg'),
('Esomeprazol 40mg'),
('Pantoprazol 40mg'),
('Lansoprazol 30mg'),
('Ranitidina 150mg'),
('Famotidina 40mg'),
('Hidróxido de Aluminio + Magnesio'),
('Sucralfato 1g'),
('Bismuto Subsalicilato'),
('Domperidona 10mg'),
('Metoclopramida 10mg'),
('Ondansetrón 8mg'),
('Loperamida 2mg'),
('Butilhioscina 10mg'),
('Trimebutina 200mg'),
('Simeticona 80mg'),
('Lactulosa'),
('Bisacodilo 5mg'),
('Senósidos 8.6mg'),
('Mesalazina 500mg'),
('Sulfasalazina 500mg'),
('Prucaloprida 2mg'),
('Rifaximina 550mg'),
('Ácido Ursodesoxicólico 300mg'),

-- RESPIRATORIOS
('Salbutamol inhalador'),
('Salbutamol jarabe'),
('Salmeterol inhalador'),
('Formoterol inhalador'),
('Budesonida inhalador'),
('Fluticasona inhalador'),
('Beclometasona inhalador'),
('Montelukast 10mg'),
('Montelukast 4mg'),
('Teofilina 200mg'),
('Bromhexina 8mg'),
('Ambroxol 30mg'),
('Ambroxol jarabe'),
('Acetilcisteína 600mg'),
('Dextrometorfano'),
('Codeína jarabe'),
('Loratadina 10mg'),
('Cetirizina 10mg'),
('Fexofenadina 120mg'),
('Desloratadina 5mg'),

-- NEUROLÓGICOS Y PSIQUIÁTRICOS
('Fluoxetina 20mg'),
('Sertralina 50mg'),
('Sertralina 100mg'),
('Paroxetina 20mg'),
('Citalopram 20mg'),
('Escitalopram 10mg'),
('Venlafaxina 75mg'),
('Duloxetina 60mg'),
('Amitriptilina 25mg'),
('Nortriptilina 25mg'),
('Clonazepam 0.5mg'),
('Clonazepam 2mg'),
('Alprazolam 0.25mg'),
('Alprazolam 0.5mg'),
('Lorazepam 1mg'),
('Diazepam 5mg'),
('Diazepam 10mg'),
('Zolpidem 10mg'),
('Quetiapina 25mg'),
('Quetiapina 100mg'),
('Olanzapina 10mg'),
('Risperidona 2mg'),
('Haloperidol 5mg'),
('Ácido Valproico 500mg'),
('Carbamazepina 200mg'),
('Fenitoína 100mg'),
('Levetiracetam 500mg'),
('Gabapentina 300mg'),
('Pregabalina 75mg'),
('Topiramato 100mg'),

-- HORMONALES
('Levotiroxina 50mcg'),
('Levotiroxina 100mcg'),
('Levotiroxina 125mcg'),
('Metimazol 5mg'),
('Propiltiouracilo 50mg'),
('Prednisona 5mg'),
('Prednisona 50mg'),
('Dexametasona 4mg'),
('Hidrocortisona 100mg'),
('Estrógenos conjugados'),
('Estradiol 1mg'),
('Progesterona 200mg'),
('Noretisterona 5mg'),
('Testosterona gel'),
('Cabergolina 0.5mg'),

-- OTROS MEDICAMENTOS COMUNES (completar hasta 403)
('Ácido Acetilsalicílico'),
('Ácido Fólico 5mg'),
('Vitamina B12'),
('Vitamina D3'),
('Calcio + Vitamina D'),
('Hierro'),
('Zinc'),
('Complejo B'),
('Vitamina C'),
('Omega 3'),
('Coenzima Q10'),
('Magnesio'),
('Potasio'),
('Alopurinol 300mg'),
('Colchicina 0.6mg'),
('Metotrexato 2.5mg'),
('Prednisona'),
('Hidrocortisona crema'),
('Betametasona crema'),
('Clotrimazol crema'),
('Ketoconazol crema'),
('Mupirocina'),
('Gentamicina crema'),
('Aciclovir 400mg'),
('Aciclovir crema'),
('Valaciclovir 500mg'),
('Famciclovir 500mg'),
('Oseltamivir 75mg'),
('Cloroquina'),
('Hidroxicloroquina'),
('Leflunomida 20mg'),
('Azatioprina 50mg'),
('Ciclosporina'),
('Tacrolimus'),
('Micofenolato'),
('Finasterida 5mg'),
('Dutasterida 0.5mg'),
('Tamsulosina 0.4mg'),
('Sildenafil 50mg'),
('Tadalafil 20mg'),
('Vardenafil 20mg'),
('Bicalutamida'),
('Letrozol'),
('Tamoxifeno'),
('Medroxiprogesterona'),
('Dienogest'),
('Drospirenona + Etinilestradiol'),
('Levonorgestrel'),
('Norgestrel'),
('Desogestrel'),
('Ciproterona + Etinilestradiol'),
('Misoprostol'),
('Oxitocina'),
('Metilergometrina'),
('Nifedipino'),
('Labetalol'),
('Hidralazina'),
('Nitroprusiato'),
('Adrenalina'),
('Noradrenalina'),
('Dopamina'),
('Dobutamina'),
('Lidocaína'),
('Bupivacaína'),
('Propofol'),
('Midazolam'),
('Ketamina'),
('Rocuronio'),
('Atropina'),
('Neostigmina'),
('Bromuro de ipratropio'),
('Tiotropio'),
('Cromoglicato'),
('Budesonida + Formoterol'),
('Fluticasona + Salmeterol'),
('Ivabradina'),
('Ranolazina'),
('Trimetazidina'),
('Apixabán'),
('Edoxabán'),
('Dabigatrán'),
('Enoxaparina'),
('Heparina'),
('Fondaparinux'),
('Alteplasa'),
('Tenecteplasa'),
('Estreptoquinasa'),
('Nimodipino'),
('Manitol'),
('Sumatriptán'),
('Naratriptán'),
('Rizatriptán'),
('Ergotamina'),
('Valproato'),
('Oxcarbazepina'),
('Lamotrigina'),
('Felbamato'),
('Etosuximida'),
('Tiagabina'),
('Vigabatrina'),
('Perampanel'),
('Lacosamida'),
('Eslicarbazepina'),
('Esketamina nasal'),
('Memantina'),
('Donepezilo'),
('Rivastigmina'),
('Galantamina'),
('Bromocriptina'),
('Pramipexol'),
('Ropinirol'),
('Rotigotina'),
('Rasagilina'),
('Selegilina'),
('Levodopa + Carbidopa'),
('Entacapona'),
('Tolcapona'),
('Amantadina'),
('Piridostigmina'),
('Edrofonio'),
('Tizanidina'),
('Baclofeno'),
('Ciclobenzaprina'),
('Metocarbamol'),
('Orfenadrina'),
('Carisoprodol'),
('Dantroleno'),
('Toxina botulínica A'),
('Toxina botulínica B'),
('Rituximab'),
('Infliximab'),
('Etanercept'),
('Adalimumab'),
('Tocilizumab'),
('Abatacept'),
('Secukinumab'),
('Ustekinumab'),
('Vedolizumab'),
('Natalizumab'),
('Fingolimod'),
('Teriflunomida'),
('Dimetilfumarato'),
('Interferón beta'),
('Acetato de glatiramer'),
('Ocrelizumab'),
('Alemtuzumab')
ON CONFLICT (name) DO NOTHING;

\echo '   ✓ 403 medicamentos insertados'
\echo ''

