#!/usr/bin/env python3
"""
Script to generate SQL migration for common medical diagnoses from Mexico
Generates CIE-10 codes for 314 additional diagnoses to reach 500 total
"""

# Common medical diagnoses from Mexico with CIE-10 codes
# Organized by specialty
# Common medical diagnoses from Mexico with CIE-10 codes
# Only includes: code, name (required fields by law)
ADDITIONAL_DIAGNOSES = [
    # Cardiology - Additional
    ('I12.9', 'Enfermedad renal hipertensiva sin insuficiencia renal'),
    ('I13.9', 'Enfermedad cardiorrenal hipertensiva, no especificada', 'Enfermedad cardiorrenal', 'Cardiología', 'severe', True, False, 'adult', 'both'),
    ('I27.9', 'Enfermedad pulmonar cardíaca, no especificada', 'Cor pulmonale', 'Cardiología', 'severe', True, False, 'adult', 'both'),
    ('I48', 'Fibrilación y aleteo auricular', 'Fibrilación auricular', 'Cardiología', 'moderate', True, False, 'adult', 'both'),
    ('I49.9', 'Arritmia cardíaca, no especificada', 'Arritmia cardíaca', 'Cardiología', 'moderate', False, False, 'all', 'both'),
    ('I70.9', 'Aterosclerosis generalizada y no especificada', 'Aterosclerosis', 'Cardiología', 'moderate', True, False, 'adult', 'both'),
    ('I73.9', 'Enfermedad vascular periférica, no especificada', 'Enfermedad vascular periférica', 'Cardiología', 'moderate', True, False, 'adult', 'both'),
    
    # Endocrinology - Additional
    ('E04.9', 'Bocio no tóxico, no especificado', 'Bocio', 'Endocrinología', 'mild', True, False, 'all', 'both'),
    ('E07.9', 'Trastorno de la tiroides, no especificado', 'Trastorno tiroideo', 'Endocrinología', 'moderate', True, False, 'all', 'both'),
    ('E11.4', 'Diabetes mellitus tipo 2 con complicaciones neurológicas', 'Diabetes tipo 2 con neuropatía', 'Endocrinología', 'severe', True, False, 'adult', 'both'),
    ('E11.5', 'Diabetes mellitus tipo 2 con complicaciones circulatorias periféricas', 'Diabetes tipo 2 con complicaciones vasculares', 'Endocrinología', 'severe', True, False, 'adult', 'both'),
    ('E11.6', 'Diabetes mellitus tipo 2 con otras complicaciones especificadas', 'Diabetes tipo 2 con otras complicaciones', 'Endocrinología', 'severe', True, False, 'adult', 'both'),
    ('E11.7', 'Diabetes mellitus tipo 2 con múltiples complicaciones', 'Diabetes tipo 2 con complicaciones múltiples', 'Endocrinología', 'severe', True, False, 'adult', 'both'),
    ('E66.0', 'Obesidad debida a exceso de calorías', 'Obesidad por exceso calórico', 'Endocrinología', 'moderate', True, False, 'all', 'both'),
    ('E66.3', 'Sobrepeso', 'Sobrepeso', 'Endocrinología', 'mild', True, False, 'all', 'both'),
    ('E78.0', 'Hipercolesterolemia pura', 'Hipercolesterolemia', 'Endocrinología', 'mild', True, False, 'adult', 'both'),
    ('E78.1', 'Hipertrigliceridemia', 'Hipertrigliceridemia', 'Endocrinología', 'mild', True, False, 'adult', 'both'),
    ('E87.6', 'Hipopotasemia', 'Hipokalemia', 'Endocrinología', 'moderate', False, False, 'all', 'both'),
    ('E87.7', 'Exceso de líquido', 'Hipervolemia', 'Endocrinología', 'mild', False, False, 'all', 'both'),
    
    # Gastroenterology - Additional
    ('K22.9', 'Enfermedad del esófago, no especificada', 'Enfermedad esofágica', 'Gastroenterología', 'moderate', False, False, 'all', 'both'),
    ('K26.9', 'Úlcera duodenal, no especificada', 'Úlcera duodenal', 'Gastroenterología', 'moderate', True, False, 'adult', 'both'),
    ('K27.9', 'Úlcera péptica, sitio no especificado', 'Úlcera péptica', 'Gastroenterología', 'moderate', True, False, 'adult', 'both'),
    ('K28.9', 'Úlcera gastro-yeyunal, no especificada', 'Úlcera gastro-yeyunal', 'Gastroenterología', 'moderate', True, False, 'adult', 'both'),
    ('K31.9', 'Enfermedad del estómago y del duodeno, no especificada', 'Enfermedad gástrica', 'Gastroenterología', 'moderate', False, False, 'all', 'both'),
    ('K58.9', 'Síndrome del intestino irritable sin diarrea', 'Síndrome de intestino irritable', 'Gastroenterología', 'moderate', True, False, 'all', 'both'),
    ('K59.2', 'Neuropatía intestinal, no clasificada en otra parte', 'Neuropatía intestinal', 'Gastroenterología', 'moderate', False, False, 'all', 'both'),
    ('K63.5', 'Polipo del colon', 'Pólipo de colon', 'Gastroenterología', 'mild', False, False, 'adult', 'both'),
    ('K65.9', 'Peritonitis, no especificada', 'Peritonitis', 'Gastroenterología', 'severe', False, False, 'all', 'both'),
    ('K70.3', 'Cirrosis hepática alcohólica', 'Cirrosis alcohólica', 'Gastroenterología', 'severe', True, False, 'adult', 'both'),
    ('K71.9', 'Enfermedad tóxica del hígado, no especificada', 'Hepatotoxicidad', 'Gastroenterología', 'moderate', False, False, 'all', 'both'),
    ('K72.9', 'Insuficiencia hepática, no especificada', 'Insuficiencia hepática', 'Gastroenterología', 'severe', False, False, 'all', 'both'),
    ('K73.9', 'Hepatitis crónica, no especificada', 'Hepatitis crónica', 'Gastroenterología', 'moderate', True, False, 'all', 'both'),
    ('K75.9', 'Enfermedad inflamatoria del hígado, no especificada', 'Enfermedad inflamatoria hepática', 'Gastroenterología', 'moderate', False, False, 'all', 'both'),
    ('K76.9', 'Enfermedad del hígado, no especificada', 'Enfermedad hepática', 'Gastroenterología', 'moderate', False, False, 'all', 'both'),
    ('K80.0', 'Cálculo de la vesícula biliar con obstrucción', 'Cálculo biliar con obstrucción', 'Gastroenterología', 'severe', False, False, 'adult', 'both'),
    ('K81.9', 'Colecistitis, no especificada', 'Colecistitis', 'Gastroenterología', 'moderate', False, False, 'adult', 'both'),
    ('K82.9', 'Enfermedad de la vesícula biliar, no especificada', 'Enfermedad de vesícula biliar', 'Gastroenterología', 'moderate', False, False, 'adult', 'both'),
    ('K83.9', 'Enfermedad de las vías biliares, no especificada', 'Enfermedad de vías biliares', 'Gastroenterología', 'moderate', False, False, 'adult', 'both'),
    ('K85.9', 'Pancreatitis aguda, no especificada', 'Pancreatitis aguda', 'Gastroenterología', 'severe', False, False, 'adult', 'both'),
    ('K86.9', 'Enfermedad del páncreas, no especificada', 'Enfermedad pancreática', 'Gastroenterología', 'moderate', False, False, 'adult', 'both'),
    ('K87', 'Trastornos de la vesícula biliar, vías biliares y páncreas en enfermedades clasificadas en otra parte', 'Trastorno biliopancreático', 'Gastroenterología', 'moderate', False, False, 'all', 'both'),
    ('K92.0', 'Hematemesis', 'Vómito con sangre', 'Gastroenterología', 'severe', False, False, 'all', 'both'),
    ('K92.1', 'Melena', 'Heces con sangre', 'Gastroenterología', 'severe', False, False, 'all', 'both'),
    ('K93.8', 'Trastornos de otros órganos digestivos especificados en enfermedades clasificadas en otra parte', 'Trastorno digestivo', 'Gastroenterología', 'moderate', False, False, 'all', 'both'),
    
    # Pulmonology - Additional
    ('J01.9', 'Sinusitis aguda, no especificada', 'Sinusitis aguda', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J02.9', 'Faringitis aguda, no especificada', 'Faringitis aguda', 'Neumología', 'moderate', False, True, 'all', 'both'),
    ('J03.9', 'Amigdalitis aguda, no especificada', 'Amigdalitis aguda', 'Neumología', 'moderate', False, True, 'all', 'both'),
    ('J04.0', 'Laringitis aguda', 'Laringitis aguda', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J05.0', 'Laringitis obstructiva aguda (crup)', 'Crup', 'Neumología', 'severe', False, False, 'pediatric', 'both'),
    ('J09.X', 'Gripe debida a virus de la gripe aviar identificado', 'Gripe aviar', 'Neumología', 'severe', False, True, 'all', 'both'),
    ('J10.1', 'Gripe con otras manifestaciones respiratorias, virus de la gripe identificado', 'Gripe con síntomas respiratorios', 'Neumología', 'moderate', False, True, 'all', 'both'),
    ('J11.1', 'Gripe con otras manifestaciones respiratorias, virus no identificado', 'Gripe sin identificar', 'Neumología', 'moderate', False, True, 'all', 'both'),
    ('J14', 'Neumonía debida a Haemophilus influenzae', 'Neumonía por H. influenzae', 'Neumología', 'moderate', False, True, 'all', 'both'),
    ('J15.0', 'Neumonía debida a Klebsiella pneumoniae', 'Neumonía por Klebsiella', 'Neumología', 'moderate', False, True, 'all', 'both'),
    ('J15.2', 'Neumonía debida a estafilococos', 'Neumonía estafilocócica', 'Neumología', 'moderate', False, True, 'all', 'both'),
    ('J16.0', 'Neumonía debida a Chlamydias', 'Neumonía por Chlamydia', 'Neumología', 'moderate', False, True, 'all', 'both'),
    ('J17', 'Neumonía en enfermedades clasificadas en otra parte', 'Neumonía secundaria', 'Neumología', 'moderate', False, True, 'all', 'both'),
    ('J18.0', 'Bronconeumonía, organismo no especificado', 'Bronconeumonía', 'Neumología', 'moderate', False, True, 'all', 'both'),
    ('J18.1', 'Neumonía lobar, organismo no especificado', 'Neumonía lobar', 'Neumología', 'moderate', False, True, 'all', 'both'),
    ('J18.2', 'Neumonía hipostática, organismo no especificado', 'Neumonía hipostática', 'Neumología', 'moderate', False, True, 'geriatric', 'both'),
    ('J19', 'Neumonía en enfermedades clasificadas en otra parte', 'Neumonía asociada', 'Neumología', 'moderate', False, True, 'all', 'both'),
    ('J21.9', 'Bronquiolitis aguda, no especificada', 'Bronquiolitis aguda', 'Neumología', 'moderate', False, True, 'pediatric', 'both'),
    ('J22', 'Infección aguda de las vías respiratorias inferiores, no especificada', 'Infección respiratoria inferior', 'Neumología', 'moderate', False, True, 'all', 'both'),
    ('J30.4', 'Rinitis alérgica, no especificada', 'Rinitis alérgica', 'Neumología', 'mild', True, False, 'all', 'both'),
    ('J31.0', 'Rinitis crónica', 'Rinitis crónica', 'Neumología', 'mild', True, False, 'all', 'both'),
    ('J32.0', 'Sinusitis maxilar crónica', 'Sinusitis maxilar crónica', 'Neumología', 'moderate', True, False, 'all', 'both'),
    ('J32.1', 'Sinusitis frontal crónica', 'Sinusitis frontal crónica', 'Neumología', 'moderate', True, False, 'all', 'both'),
    ('J32.2', 'Sinusitis etmoidal crónica', 'Sinusitis etmoidal crónica', 'Neumología', 'moderate', True, False, 'all', 'both'),
    ('J32.3', 'Sinusitis esfenoidal crónica', 'Sinusitis esfenoidal crónica', 'Neumología', 'moderate', True, False, 'all', 'both'),
    ('J32.4', 'Pansinusitis crónica', 'Pansinusitis crónica', 'Neumología', 'moderate', True, False, 'all', 'both'),
    ('J33.9', 'Pólipo nasal, no especificado', 'Pólipo nasal', 'Neumología', 'mild', False, False, 'all', 'both'),
    ('J34.3', 'Hipertrofia de cornetes nasales', 'Hipertrofia de cornetes', 'Neumología', 'mild', False, False, 'all', 'both'),
    ('J35.0', 'Amigdalitis crónica', 'Amigdalitis crónica', 'Neumología', 'moderate', True, False, 'all', 'both'),
    ('J35.1', 'Hipertrofia de las amígdalas', 'Hipertrofia amigdalar', 'Neumología', 'mild', False, False, 'pediatric', 'both'),
    ('J35.2', 'Hipertrofia de las adenoides', 'Hipertrofia adenoidea', 'Neumología', 'mild', False, False, 'pediatric', 'both'),
    ('J35.3', 'Hipertrofia de las amígdalas con hipertrofia de las adenoides', 'Hipertrofia amigdalar y adenoidea', 'Neumología', 'mild', False, False, 'pediatric', 'both'),
    ('J36', 'Absceso periamigdalino', 'Absceso periamigdalino', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J37.0', 'Laringitis crónica', 'Laringitis crónica', 'Neumología', 'moderate', True, False, 'all', 'both'),
    ('J37.1', 'Laringotraqueítis crónica', 'Laringotraqueítis crónica', 'Neumología', 'moderate', True, False, 'all', 'both'),
    ('J38.0', 'Parálisis de las cuerdas vocales y de la laringe', 'Parálisis de cuerdas vocales', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J38.1', 'Pólipo de las cuerdas vocales y de la laringe', 'Pólipo de cuerdas vocales', 'Neumología', 'mild', False, False, 'all', 'both'),
    ('J38.2', 'Nódulos de las cuerdas vocales', 'Nódulos de cuerdas vocales', 'Neumología', 'mild', False, False, 'all', 'both'),
    ('J38.3', 'Otras enfermedades de las cuerdas vocales', 'Enfermedad de cuerdas vocales', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J38.4', 'Edema de la laringe', 'Edema laríngeo', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J38.5', 'Espasmo laríngeo', 'Espasmo laríngeo', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J38.6', 'Estenosis de la laringe', 'Estenosis laríngea', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J38.7', 'Otras enfermedades de la laringe', 'Enfermedad laríngea', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J39.0', 'Absceso retrofaríngeo y parafaríngeo', 'Absceso retrofaríngeo', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J39.1', 'Otro absceso de la faringe', 'Absceso faríngeo', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J39.2', 'Otras enfermedades de la faringe', 'Enfermedad faríngea', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J39.3', 'Reacción de hipersensibilidad de las vías respiratorias superiores, sitio no especificado', 'Hipersensibilidad respiratoria', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J39.8', 'Otras enfermedades especificadas de las vías respiratorias superiores', 'Enfermedad respiratoria superior', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J39.9', 'Enfermedad de las vías respiratorias superiores, no especificada', 'Enfermedad respiratoria superior', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J40', 'Bronquitis, no especificada como aguda o crónica', 'Bronquitis', 'Neumología', 'moderate', False, True, 'all', 'both'),
    ('J41.0', 'Bronquitis crónica simple', 'Bronquitis crónica simple', 'Neumología', 'moderate', True, False, 'adult', 'both'),
    ('J41.1', 'Bronquitis crónica mucopurulenta', 'Bronquitis crónica mucopurulenta', 'Neumología', 'moderate', True, False, 'adult', 'both'),
    ('J41.8', 'Bronquitis crónica mixta simple y mucopurulenta', 'Bronquitis crónica mixta', 'Neumología', 'moderate', True, False, 'adult', 'both'),
    ('J42', 'Bronquitis crónica, no especificada', 'Bronquitis crónica', 'Neumología', 'moderate', True, False, 'adult', 'both'),
    ('J43.0', 'Enfisema de Macleod', 'Enfisema de Macleod', 'Neumología', 'moderate', True, False, 'adult', 'both'),
    ('J43.1', 'Enfisema panlobulillar', 'Enfisema panlobulillar', 'Neumología', 'moderate', True, False, 'adult', 'both'),
    ('J43.2', 'Enfisema centrolobulillar', 'Enfisema centrolobulillar', 'Neumología', 'moderate', True, False, 'adult', 'both'),
    ('J43.8', 'Otro enfisema', 'Otro enfisema', 'Neumología', 'moderate', True, False, 'adult', 'both'),
    ('J43.9', 'Enfisema, no especificado', 'Enfisema', 'Neumología', 'moderate', True, False, 'adult', 'both'),
    ('J44.1', 'Enfermedad pulmonar obstructiva crónica con exacerbación aguda, no especificada', 'EPOC con exacerbación', 'Neumología', 'severe', True, False, 'adult', 'both'),
    ('J45.0', 'Asma predominantemente alérgica', 'Asma alérgica', 'Neumología', 'moderate', True, False, 'all', 'both'),
    ('J45.1', 'Asma no alérgica', 'Asma no alérgica', 'Neumología', 'moderate', True, False, 'all', 'both'),
    ('J45.8', 'Asma mixta', 'Asma mixta', 'Neumología', 'moderate', True, False, 'all', 'both'),
    ('J46', 'Estado asmático', 'Estado asmático', 'Neumología', 'severe', False, False, 'all', 'both'),
    ('J47', 'Bronquiectasia', 'Bronquiectasia', 'Neumología', 'moderate', True, False, 'all', 'both'),
    ('J60', 'Neumoconiosis de los mineros del carbón', 'Neumoconiosis del minero', 'Neumología', 'moderate', True, False, 'adult', 'both'),
    ('J64', 'Neumoconiosis, no especificada', 'Neumoconiosis', 'Neumología', 'moderate', True, False, 'adult', 'both'),
    ('J67.9', 'Neumonitis por hipersensibilidad debida a polvo orgánico no especificado', 'Neumonitis por hipersensibilidad', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J68.9', 'Afecciones respiratorias debidas a inhalación de productos químicos, gases, humos y vapores, no especificadas', 'Enfermedad respiratoria por inhalación', 'Neumología', 'moderate', False, False, 'adult', 'both'),
    ('J69.0', 'Neumonía debida a alimentos y vómitos', 'Neumonía por aspiración', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J69.8', 'Neumonía debida a otros sólidos y líquidos', 'Neumonía por aspiración de líquidos', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J70.9', 'Afecciones respiratorias debidas a otras sustancias externas, no especificadas', 'Enfermedad respiratoria por sustancias externas', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J80', 'Síndrome de dificultad respiratoria del adulto', 'SDRA', 'Neumología', 'severe', False, False, 'adult', 'both'),
    ('J81', 'Edema pulmonar, no especificado', 'Edema pulmonar', 'Neumología', 'severe', False, False, 'all', 'both'),
    ('J82', 'Eosinofilia pulmonar, no clasificada en otra parte', 'Eosinofilia pulmonar', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J84.9', 'Enfermedad pulmonar intersticial, no especificada', 'Enfermedad pulmonar intersticial', 'Neumología', 'moderate', True, False, 'all', 'both'),
    ('J85.0', 'Gangrena y necrosis del pulmón', 'Gangrena pulmonar', 'Neumología', 'severe', False, False, 'all', 'both'),
    ('J85.1', 'Absceso del pulmón con neumonía', 'Absceso pulmonar con neumonía', 'Neumología', 'severe', False, False, 'all', 'both'),
    ('J85.2', 'Absceso del pulmón sin neumonía', 'Absceso pulmonar', 'Neumología', 'severe', False, False, 'all', 'both'),
    ('J85.3', 'Absceso del mediastino', 'Absceso mediastínico', 'Neumología', 'severe', False, False, 'all', 'both'),
    ('J86.0', 'Piótorax con fístula', 'Piótorax con fístula', 'Neumología', 'severe', False, False, 'all', 'both'),
    ('J86.9', 'Piótorax sin fístula', 'Piótorax', 'Neumología', 'severe', False, False, 'all', 'both'),
    ('J90', 'Derrame pleural, no clasificado en otra parte', 'Derrame pleural', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J91', 'Derrame pleural en afecciones clasificadas en otra parte', 'Derrame pleural secundario', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J92.0', 'Placa pleural con asbestosis', 'Placa pleural con asbestosis', 'Neumología', 'moderate', True, False, 'adult', 'both'),
    ('J92.9', 'Placa pleural sin asbestosis', 'Placa pleural', 'Neumología', 'mild', False, False, 'adult', 'both'),
    ('J93.0', 'Neumotórax espontáneo con tensión', 'Neumotórax a tensión', 'Neumología', 'severe', False, False, 'all', 'both'),
    ('J93.1', 'Neumotórax espontáneo sin tensión', 'Neumotórax espontáneo', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J93.8', 'Otro neumotórax', 'Otro neumotórax', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J93.9', 'Neumotórax, no especificado', 'Neumotórax', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J94.0', 'Quilotórax', 'Quilotórax', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J94.1', 'Fibrótorax', 'Fibrótorax', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J94.2', 'Hemotórax', 'Hemotórax', 'Neumología', 'severe', False, False, 'all', 'both'),
    ('J94.8', 'Otras afecciones pleurales especificadas', 'Otra afección pleural', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J94.9', 'Afección pleural, no especificada', 'Afección pleural', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J95.0', 'Disfunción de traqueostomía', 'Disfunción de traqueostomía', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J95.1', 'Insuficiencia pulmonar aguda consecutiva a cirugía', 'Insuficiencia pulmonar postquirúrgica', 'Neumología', 'severe', False, False, 'all', 'both'),
    ('J95.2', 'Insuficiencia pulmonar aguda consecutiva a procedimiento no quirúrgico', 'Insuficiencia pulmonar postprocedimiento', 'Neumología', 'severe', False, False, 'all', 'both'),
    ('J95.3', 'Insuficiencia pulmonar crónica consecutiva a cirugía', 'Insuficiencia pulmonar crónica postquirúrgica', 'Neumología', 'moderate', True, False, 'all', 'both'),
    ('J95.4', 'Síndrome de Mendelson', 'Síndrome de Mendelson', 'Neumología', 'severe', False, False, 'all', 'both'),
    ('J95.8', 'Otras afecciones respiratorias consecutivas a procedimientos', 'Afección respiratoria postprocedimiento', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J95.9', 'Afección respiratoria consecutiva a procedimiento, no especificada', 'Afección respiratoria postprocedimiento', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J96.0', 'Insuficiencia respiratoria aguda', 'Insuficiencia respiratoria aguda', 'Neumología', 'severe', False, False, 'all', 'both'),
    ('J96.1', 'Insuficiencia respiratoria crónica', 'Insuficiencia respiratoria crónica', 'Neumología', 'severe', True, False, 'all', 'both'),
    ('J96.9', 'Insuficiencia respiratoria, no especificada', 'Insuficiencia respiratoria', 'Neumología', 'severe', False, False, 'all', 'both'),
    ('J98.0', 'Enfermedades de la tráquea y de los bronquios, no clasificadas en otra parte', 'Enfermedad traqueobronquial', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J98.1', 'Colapso pulmonar', 'Atelectasia', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J98.2', 'Enfisema intersticial', 'Enfisema intersticial', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J98.3', 'Enfisema compensatorio', 'Enfisema compensatorio', 'Neumología', 'mild', False, False, 'all', 'both'),
    ('J98.4', 'Otros trastornos del pulmón', 'Otro trastorno pulmonar', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J98.5', 'Enfermedades del mediastino, no clasificadas en otra parte', 'Enfermedad mediastínica', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J98.6', 'Trastornos del diafragma', 'Trastorno diafragmático', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J98.8', 'Otras afecciones respiratorias especificadas', 'Otra afección respiratoria', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J98.9', 'Afección respiratoria, no especificada', 'Afección respiratoria', 'Neumología', 'moderate', False, False, 'all', 'both'),
    ('J99', 'Afecciones respiratorias en enfermedades clasificadas en otra parte', 'Afección respiratoria asociada', 'Neumología', 'moderate', False, False, 'all', 'both'),
    
    # Neurology - Additional
    ('G00.9', 'Meningitis bacteriana, no especificada', 'Meningitis bacteriana', 'Neurología', 'severe', False, True, 'all', 'both'),
    ('G03.9', 'Meningitis, no especificada', 'Meningitis', 'Neurología', 'severe', False, True, 'all', 'both'),
    ('G04.9', 'Encefalitis, mielitis y encefalomielitis, no especificada', 'Encefalitis', 'Neurología', 'severe', False, True, 'all', 'both'),
    ('G10', 'Enfermedad de Huntington', 'Enfermedad de Huntington', 'Neurología', 'severe', True, False, 'all', 'both'),
    ('G11.9', 'Ataxia hereditaria, no especificada', 'Ataxia hereditaria', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G12.9', 'Atrofia muscular espinal, no especificada', 'Atrofia muscular espinal', 'Neurología', 'severe', True, False, 'all', 'both'),
    ('G20', 'Enfermedad de Parkinson', 'Enfermedad de Parkinson', 'Neurología', 'moderate', True, False, 'adult', 'both'),
    ('G21.9', 'Parkinsonismo secundario, no especificado', 'Parkinsonismo secundario', 'Neurología', 'moderate', True, False, 'adult', 'both'),
    ('G24.9', 'Distonía, no especificada', 'Distonía', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G31.9', 'Degeneración del sistema nervioso, no especificada', 'Degeneración del sistema nervioso', 'Neurología', 'severe', True, False, 'adult', 'both'),
    ('G35', 'Esclerosis múltiple', 'Esclerosis múltiple', 'Neurología', 'severe', True, False, 'all', 'both'),
    ('G36.9', 'Otro desmielinización aguda diseminada, no especificada', 'Desmielinización aguda', 'Neurología', 'severe', False, False, 'all', 'both'),
    ('G37.9', 'Otra enfermedad desmielinizante del sistema nervioso central, no especificada', 'Enfermedad desmielinizante', 'Neurología', 'severe', True, False, 'all', 'both'),
    ('G40.0', 'Epilepsia localizada (focal) (parcial) idiopática', 'Epilepsia focal idiopática', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G40.1', 'Epilepsia localizada (focal) (parcial) sintomática', 'Epilepsia focal sintomática', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G40.2', 'Epilepsia localizada (focal) (parcial) criptogénica', 'Epilepsia focal criptogénica', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G40.3', 'Epilepsia generalizada idiopática', 'Epilepsia generalizada idiopática', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G40.4', 'Otras epilepsias generalizadas', 'Otras epilepsias generalizadas', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G40.5', 'Epilepsias especiales', 'Epilepsias especiales', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G40.6', 'Crisis de gran mal, no especificadas (con o sin pequeño mal)', 'Crisis de gran mal', 'Neurología', 'moderate', False, False, 'all', 'both'),
    ('G40.7', 'Crisis de pequeño mal, no especificadas, sin crisis de gran mal', 'Crisis de pequeño mal', 'Neurología', 'moderate', False, False, 'all', 'both'),
    ('G40.8', 'Otras epilepsias', 'Otras epilepsias', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G41.0', 'Estado de gran mal', 'Estado epiléptico de gran mal', 'Neurología', 'severe', False, False, 'all', 'both'),
    ('G41.1', 'Estado de pequeño mal', 'Estado epiléptico de pequeño mal', 'Neurología', 'severe', False, False, 'all', 'both'),
    ('G41.2', 'Estado parcial complejo', 'Estado epiléptico parcial complejo', 'Neurología', 'severe', False, False, 'all', 'both'),
    ('G41.8', 'Otro estado epiléptico', 'Otro estado epiléptico', 'Neurología', 'severe', False, False, 'all', 'both'),
    ('G41.9', 'Estado epiléptico, no especificado', 'Estado epiléptico', 'Neurología', 'severe', False, False, 'all', 'both'),
    ('G43.0', 'Migraña sin aura (migraña común)', 'Migraña sin aura', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G43.1', 'Migraña con aura (migraña clásica)', 'Migraña con aura', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G43.2', 'Estado de mal migrañoso', 'Estado de mal migrañoso', 'Neurología', 'severe', False, False, 'all', 'both'),
    ('G43.3', 'Migraña complicada', 'Migraña complicada', 'Neurología', 'severe', False, False, 'all', 'both'),
    ('G43.8', 'Otras migrañas', 'Otras migrañas', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G44.0', 'Síndrome de cefalea en racimos', 'Cefalea en racimos', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G44.2', 'Cefalea de tipo tensional', 'Cefalea tensional', 'Neurología', 'mild', False, False, 'all', 'both'),
    ('G44.3', 'Cefalea postraumática crónica', 'Cefalea postraumática', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G44.4', 'Cefalea inducida por medicamentos, no clasificada en otra parte', 'Cefalea por medicamentos', 'Neurología', 'mild', False, False, 'all', 'both'),
    ('G44.8', 'Otras síndromes de cefalea especificadas', 'Otro síndrome de cefalea', 'Neurología', 'moderate', False, False, 'all', 'both'),
    ('G47.0', 'Trastornos de inicio y mantenimiento del sueño (insomnio)', 'Insomnio', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G47.1', 'Trastornos de somnolencia excesiva (hipersomnia)', 'Hipersomnia', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G47.2', 'Trastornos del ciclo sueño-vigilia', 'Trastorno del ritmo circadiano', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G47.3', 'Apnea del sueño', 'Apnea del sueño', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G47.4', 'Narcolepsia y cataplejía', 'Narcolepsia', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G47.8', 'Otros trastornos del sueño', 'Otro trastorno del sueño', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G47.9', 'Trastorno del sueño, no especificado', 'Trastorno del sueño', 'Neurología', 'moderate', False, False, 'all', 'both'),
    ('G51.0', 'Parálisis de Bell', 'Parálisis de Bell', 'Neurología', 'moderate', False, False, 'all', 'both'),
    ('G52.9', 'Trastorno de nervio craneal, no especificado', 'Trastorno de nervio craneal', 'Neurología', 'moderate', False, False, 'all', 'both'),
    ('G54.9', 'Trastorno del plexo, no especificado', 'Trastorno del plexo', 'Neurología', 'moderate', False, False, 'all', 'both'),
    ('G56.9', 'Mononeuropatía del miembro superior, no especificada', 'Mononeuropatía del miembro superior', 'Neurología', 'moderate', False, False, 'all', 'both'),
    ('G57.9', 'Mononeuropatía del miembro inferior, no especificada', 'Mononeuropatía del miembro inferior', 'Neurología', 'moderate', False, False, 'all', 'both'),
    ('G58.9', 'Otra mononeuropatía, no especificada', 'Otra mononeuropatía', 'Neurología', 'moderate', False, False, 'all', 'both'),
    ('G59.9', 'Mononeuropatía en enfermedades clasificadas en otra parte, no especificada', 'Mononeuropatía secundaria', 'Neurología', 'moderate', False, False, 'all', 'both'),
    ('G60.9', 'Neuropatía hereditaria e idiopática, no especificada', 'Neuropatía hereditaria', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G61.9', 'Polineuropatía inflamatoria, no especificada', 'Polineuropatía inflamatoria', 'Neurología', 'moderate', False, False, 'all', 'both'),
    ('G62.9', 'Polineuropatía, no especificada', 'Polineuropatía', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G63.9', 'Polineuropatía en enfermedades clasificadas en otra parte, no especificada', 'Polineuropatía secundaria', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G64', 'Otros trastornos del sistema nervioso periférico', 'Trastorno del sistema nervioso periférico', 'Neurología', 'moderate', False, False, 'all', 'both'),
    ('G70.9', 'Miastenia gravis y otros trastornos neuromusculares, no especificados', 'Miastenia gravis', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G71.9', 'Distrofia muscular, no especificada', 'Distrofia muscular', 'Neurología', 'severe', True, False, 'all', 'both'),
    ('G72.9', 'Miopatía, no especificada', 'Miopatía', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G73.9', 'Trastornos de la unión neuromuscular y del músculo en enfermedades clasificadas en otra parte, no especificados', 'Trastorno neuromuscular', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G80.9', 'Parálisis cerebral, no especificada', 'Parálisis cerebral', 'Neurología', 'severe', True, False, 'pediatric', 'both'),
    ('G81.9', 'Hemiplejía, no especificada', 'Hemiplejía', 'Neurología', 'severe', True, False, 'all', 'both'),
    ('G82.9', 'Paraplejía y tetraplejía, no especificada', 'Paraplejía', 'Neurología', 'severe', True, False, 'all', 'both'),
    ('G83.9', 'Otros síndromes paralíticos, no especificados', 'Síndrome paralítico', 'Neurología', 'severe', True, False, 'all', 'both'),
    ('G90.9', 'Trastorno del sistema nervioso autónomo, no especificado', 'Trastorno del sistema nervioso autónomo', 'Neurología', 'moderate', True, False, 'all', 'both'),
    ('G92', 'Encefalopatía tóxica', 'Encefalopatía tóxica', 'Neurología', 'severe', False, False, 'all', 'both'),
    ('G93.0', 'Quiste cerebral', 'Quiste cerebral', 'Neurología', 'moderate', False, False, 'all', 'both'),
    ('G93.2', 'Hipertensión intracraneal benigna', 'Hipertensión intracraneal', 'Neurología', 'moderate', False, False, 'all', 'both'),
    ('G93.3', 'Encefalopatía postvirica, no especificada', 'Encefalopatía postvirica', 'Neurología', 'moderate', False, False, 'all', 'both'),
    ('G93.4', 'Encefalopatía, no especificada', 'Encefalopatía', 'Neurología', 'moderate', False, False, 'all', 'both'),
    ('G93.5', 'Compresión del encéfalo', 'Compresión cerebral', 'Neurología', 'severe', False, False, 'all', 'both'),
    ('G93.6', 'Edema cerebral', 'Edema cerebral', 'Neurología', 'severe', False, False, 'all', 'both'),
    ('G93.7', 'Síndrome de Reye', 'Síndrome de Reye', 'Neurología', 'severe', False, False, 'pediatric', 'both'),
    ('G93.8', 'Otras enfermedades especificadas del encéfalo', 'Otra enfermedad cerebral', 'Neurología', 'moderate', False, False, 'all', 'both'),
    ('G93.9', 'Enfermedad del encéfalo, no especificada', 'Enfermedad cerebral', 'Neurología', 'moderate', False, False, 'all', 'both'),
    ('G94', 'Otros trastornos del encéfalo en enfermedades clasificadas en otra parte', 'Trastorno cerebral secundario', 'Neurología', 'moderate', False, False, 'all', 'both'),
    ('G95.9', 'Enfermedad de la médula espinal, no especificada', 'Enfermedad de la médula espinal', 'Neurología', 'severe', True, False, 'all', 'both'),
    ('G96.9', 'Trastorno del sistema nervioso central, no especificado', 'Trastorno del sistema nervioso central', 'Neurología', 'moderate', False, False, 'all', 'both'),
    ('G97.9', 'Trastorno del sistema nervioso consecutivo a procedimiento, no especificado', 'Trastorno neurológico postprocedimiento', 'Neurología', 'moderate', False, False, 'all', 'both'),
    ('G98.9', 'Otros trastornos del sistema nervioso, no especificados', 'Otro trastorno neurológico', 'Neurología', 'moderate', False, False, 'all', 'both'),
    ('G99.9', 'Trastornos del sistema nervioso en enfermedades clasificadas en otra parte, no especificados', 'Trastorno neurológico secundario', 'Neurología', 'moderate', False, False, 'all', 'both'),
    
    # Orthopedics and Musculoskeletal - Additional
    ('M00.9', 'Artritis piógena, no especificada', 'Artritis séptica', 'Traumatología', 'severe', False, False, 'all', 'both'),
    ('M01.X', 'Infección directa de articulación en enfermedades infecciosas y parasitarias clasificadas en otra parte', 'Artritis infecciosa', 'Traumatología', 'severe', False, True, 'all', 'both'),
    ('M02.9', 'Artropatía reactiva, no especificada', 'Artropatía reactiva', 'Reumatología', 'moderate', False, False, 'all', 'both'),
    ('M03.9', 'Artropatía postinfecciosa y reactiva en enfermedades clasificadas en otra parte, no especificada', 'Artropatía postinfecciosa', 'Reumatología', 'moderate', False, False, 'all', 'both'),
    ('M05.9', 'Artritis reumatoide seropositiva, no especificada', 'Artritis reumatoide seropositiva', 'Reumatología', 'moderate', True, False, 'all', 'both'),
    ('M07.9', 'Artropatía psoriásica y enteropática, no especificada', 'Artropatía psoriásica', 'Reumatología', 'moderate', True, False, 'all', 'both'),
    ('M08.9', 'Artritis juvenil, no especificada', 'Artritis juvenil', 'Reumatología', 'moderate', True, False, 'pediatric', 'both'),
    ('M09.9', 'Artritis juvenil en enfermedades clasificadas en otra parte, no especificada', 'Artritis juvenil secundaria', 'Reumatología', 'moderate', True, False, 'pediatric', 'both'),
    ('M10.9', 'Gota, no especificada', 'Gota', 'Reumatología', 'moderate', True, False, 'adult', 'both'),
    ('M11.9', 'Otras artropatías por depósito de cristales, no especificadas', 'Artropatía por cristales', 'Reumatología', 'moderate', False, False, 'adult', 'both'),
    ('M12.9', 'Otras artropatías especificadas, no especificadas', 'Otra artropatía', 'Reumatología', 'moderate', False, False, 'all', 'both'),
    ('M13.9', 'Artritis, no especificada', 'Artritis', 'Reumatología', 'moderate', False, False, 'all', 'both'),
    ('M14.9', 'Artropatía en otras enfermedades clasificadas en otra parte, no especificada', 'Artropatía secundaria', 'Reumatología', 'moderate', False, False, 'all', 'both'),
    ('M16.9', 'Coxartrosis (artrosis de cadera), no especificada', 'Artrosis de cadera', 'Reumatología', 'moderate', True, False, 'adult', 'both'),
    ('M17.9', 'Gonartrosis (artrosis de rodilla), no especificada', 'Artrosis de rodilla', 'Reumatología', 'moderate', True, False, 'adult', 'both'),
    ('M18.9', 'Artrosis de la primera articulación carpometacarpiana, no especificada', 'Artrosis de pulgar', 'Reumatología', 'moderate', True, False, 'adult', 'both'),
    ('M20.9', 'Deformidad adquirida de los dedos de la mano y del pie, no especificada', 'Deformidad de dedos', 'Traumatología', 'mild', False, False, 'all', 'both'),
    ('M21.9', 'Otra deformidad adquirida de miembro, no especificada', 'Deformidad de miembro', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M22.9', 'Trastorno de la rótula, no especificado', 'Trastorno de rótula', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M23.9', 'Trastorno interno de la rodilla, no especificado', 'Trastorno interno de rodilla', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M24.9', 'Otros trastornos articulares específicos, no especificados', 'Otro trastorno articular', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M25.0', 'Hemartrosis', 'Hemartrosis', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M25.1', 'Fístula articular', 'Fístula articular', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M25.2', 'Flail joint', 'Articulación laxa', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M25.3', 'Otra inestabilidad articular', 'Inestabilidad articular', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M25.4', 'Derrame articular', 'Derrame articular', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M25.7', 'Osteofito', 'Osteofito', 'Traumatología', 'mild', False, False, 'adult', 'both'),
    ('M25.8', 'Otros trastornos articulares específicos', 'Otro trastorno articular', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M25.9', 'Trastorno articular, no especificado', 'Trastorno articular', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M26.9', 'Deformidades dentofaciales (incluye maloclusión), no especificada', 'Deformidad dentofacial', 'Traumatología', 'mild', False, False, 'all', 'both'),
    ('M27.9', 'Otras enfermedades de los maxilares, no especificadas', 'Enfermedad de maxilares', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M30.9', 'Poliarteritis nodosa y afecciones relacionadas, no especificada', 'Poliarteritis nodosa', 'Reumatología', 'severe', True, False, 'all', 'both'),
    ('M31.9', 'Otras vasculopatías necrosantes, no especificada', 'Vasculopatía necrosante', 'Reumatología', 'severe', True, False, 'all', 'both'),
    ('M33.9', 'Dermatomiositis, no especificada', 'Dermatomiositis', 'Reumatología', 'severe', True, False, 'all', 'both'),
    ('M34.9', 'Esclerosis sistémica, no especificada', 'Esclerosis sistémica', 'Reumatología', 'severe', True, False, 'all', 'both'),
    ('M36.9', 'Sistemopatías del tejido conectivo en enfermedades clasificadas en otra parte, no especificada', 'Sistemopatía del tejido conectivo', 'Reumatología', 'moderate', True, False, 'all', 'both'),
    ('M40.9', 'Cifosis y lordosis, no especificada', 'Cifosis', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M41.9', 'Escoliosis, no especificada', 'Escoliosis', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M42.9', 'Osteocondrosis de la columna vertebral, no especificada', 'Osteocondrosis vertebral', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M43.9', 'Otras deformidades adquiridas de la columna vertebral y del cuello, no especificadas', 'Deformidad de columna', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M45.9', 'Espondilitis anquilosante, no especificada', 'Espondilitis anquilosante', 'Reumatología', 'moderate', True, False, 'adult', 'both'),
    ('M46.9', 'Otras espondilopatías inflamatorias, no especificada', 'Espondilopatía inflamatoria', 'Reumatología', 'moderate', True, False, 'all', 'both'),
    ('M47.9', 'Espondilosis, no especificada', 'Espondilosis', 'Reumatología', 'moderate', True, False, 'adult', 'both'),
    ('M48.9', 'Otras espondilopatías, no especificada', 'Otra espondilopatía', 'Reumatología', 'moderate', False, False, 'all', 'both'),
    ('M49.9', 'Espondilopatías en enfermedades clasificadas en otra parte, no especificada', 'Espondilopatía secundaria', 'Reumatología', 'moderate', False, False, 'all', 'both'),
    ('M50.9', 'Trastorno de disco cervical, no especificado', 'Trastorno de disco cervical', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M51.9', 'Trastorno de disco intervertebral, no especificado', 'Trastorno de disco intervertebral', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M53.9', 'Otros trastornos de la columna dorsal y dorsolumbar, no especificados', 'Trastorno de columna', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M54.0', 'Paniculitis que afecta regiones del cuello y de la espalda', 'Paniculitis cervical', 'Reumatología', 'mild', False, False, 'all', 'both'),
    ('M54.3', 'Ciática', 'Ciática', 'Neurología', 'moderate', False, False, 'adult', 'both'),
    ('M54.4', 'Lumbago con ciática', 'Lumbago con ciática', 'Neurología', 'moderate', False, False, 'adult', 'both'),
    ('M54.6', 'Dolor en la columna torácica', 'Dolor torácico vertebral', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M54.8', 'Otras dorsalgias', 'Otra dorsalgia', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M60.9', 'Miositis, no especificada', 'Miositis', 'Reumatología', 'moderate', False, False, 'all', 'both'),
    ('M61.9', 'Calcificación y osificación del músculo, no especificada', 'Calcificación muscular', 'Reumatología', 'moderate', False, False, 'all', 'both'),
    ('M62.9', 'Otros trastornos del músculo, no especificados', 'Otro trastorno muscular', 'Reumatología', 'moderate', False, False, 'all', 'both'),
    ('M63.9', 'Trastornos del músculo en enfermedades clasificadas en otra parte, no especificados', 'Trastorno muscular secundario', 'Reumatología', 'moderate', False, False, 'all', 'both'),
    ('M65.9', 'Sinovitis y tenosinovitis, no especificada', 'Sinovitis', 'Reumatología', 'moderate', False, False, 'all', 'both'),
    ('M66.9', 'Ruptura espontánea de sinovia y de tendón, no especificada', 'Ruptura de tendón', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M67.9', 'Trastorno de la sinovia y del tendón, no especificado', 'Trastorno de tendón', 'Reumatología', 'moderate', False, False, 'all', 'both'),
    ('M68.9', 'Trastorno de la sinovia y del tendón en enfermedades clasificadas en otra parte, no especificado', 'Trastorno de tendón secundario', 'Reumatología', 'moderate', False, False, 'all', 'both'),
    ('M70.9', 'Trastornos de los tejidos blandos relacionados con el uso, el sobreuso y la presión, no especificado', 'Trastorno por sobreuso', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M71.9', 'Otras bursopatías, no especificada', 'Bursitis', 'Reumatología', 'moderate', False, False, 'all', 'both'),
    ('M72.9', 'Trastornos fibroblásticos, no especificado', 'Trastorno fibroblástico', 'Reumatología', 'moderate', False, False, 'all', 'both'),
    ('M73.9', 'Trastornos de los tejidos blandos en enfermedades clasificadas en otra parte, no especificado', 'Trastorno de tejidos blandos', 'Reumatología', 'moderate', False, False, 'all', 'both'),
    ('M75.9', 'Lesión del hombro, no especificada', 'Lesión de hombro', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M76.9', 'Entesopatías de miembro inferior, excluido pie, no especificada', 'Entesopatía de miembro inferior', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M77.9', 'Otras entesopatías, no especificada', 'Otra entesopatía', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M79.0', 'Reumatismo, no especificado', 'Reumatismo', 'Reumatología', 'moderate', False, False, 'all', 'both'),
    ('M79.1', 'Mialgia', 'Mialgia', 'Reumatología', 'mild', False, False, 'all', 'both'),
    ('M79.2', 'Neuralgia y neuritis, no especificadas', 'Neuralgia', 'Neurología', 'moderate', False, False, 'all', 'both'),
    ('M79.4', 'Hipertrofia del (del los) cuerpo(s) graso(s) de la rodilla', 'Hipertrofia del cuerpo graso', 'Traumatología', 'mild', False, False, 'all', 'both'),
    ('M79.5', 'Cuerpo residual en tejido blando', 'Cuerpo residual', 'Traumatología', 'mild', False, False, 'all', 'both'),
    ('M79.8', 'Otros trastornos de los tejidos blandos especificados', 'Otro trastorno de tejidos blandos', 'Reumatología', 'moderate', False, False, 'all', 'both'),
    ('M79.9', 'Trastorno de los tejidos blandos, no especificado', 'Trastorno de tejidos blandos', 'Reumatología', 'moderate', False, False, 'all', 'both'),
    ('M80.9', 'Osteoporosis con fractura patológica, no especificada', 'Osteoporosis con fractura', 'Reumatología', 'severe', True, False, 'adult', 'both'),
    ('M81.9', 'Osteoporosis sin fractura patológica, no especificada', 'Osteoporosis', 'Reumatología', 'moderate', True, False, 'adult', 'both'),
    ('M82.9', 'Osteoporosis en enfermedades clasificadas en otra parte, no especificada', 'Osteoporosis secundaria', 'Reumatología', 'moderate', True, False, 'all', 'both'),
    ('M83.9', 'Osteomalacia del adulto, no especificada', 'Osteomalacia', 'Reumatología', 'moderate', False, False, 'adult', 'both'),
    ('M84.9', 'Trastorno de la continuidad del hueso, no especificado', 'Trastorno de continuidad ósea', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M85.9', 'Trastorno de la densidad y de la estructura óseas, no especificado', 'Trastorno de densidad ósea', 'Reumatología', 'moderate', False, False, 'all', 'both'),
    ('M86.9', 'Osteomielitis, no especificada', 'Osteomielitis', 'Traumatología', 'severe', False, True, 'all', 'both'),
    ('M87.9', 'Necrosis aséptica del hueso, no especificada', 'Necrosis ósea', 'Traumatología', 'severe', False, False, 'all', 'both'),
    ('M88.9', 'Enfermedad de Paget del hueso (osteítis deformante), no especificada', 'Enfermedad de Paget', 'Reumatología', 'moderate', True, False, 'adult', 'both'),
    ('M89.9', 'Otros trastornos del hueso, no especificados', 'Otro trastorno óseo', 'Reumatología', 'moderate', False, False, 'all', 'both'),
    ('M90.9', 'Osteopatía en enfermedades clasificadas en otra parte, no especificada', 'Osteopatía secundaria', 'Reumatología', 'moderate', False, False, 'all', 'both'),
    ('M91.9', 'Osteocondrosis juvenil de cadera y pelvis, no especificada', 'Osteocondrosis juvenil', 'Traumatología', 'moderate', False, False, 'pediatric', 'both'),
    ('M92.9', 'Otras osteocondrosis juveniles, no especificadas', 'Otra osteocondrosis juvenil', 'Traumatología', 'moderate', False, False, 'pediatric', 'both'),
    ('M93.9', 'Otras osteocondropatías, no especificadas', 'Otra osteocondropatía', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M94.9', 'Otros trastornos del cartílago, no especificados', 'Otro trastorno del cartílago', 'Reumatología', 'moderate', False, False, 'all', 'both'),
    ('M95.9', 'Otras deformidades adquiridas del sistema musculoesquelético y del tejido conjuntivo, no especificada', 'Deformidad musculoesquelética', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M96.9', 'Trastornos musculoesqueléticos consecutivos a procedimientos, no especificado', 'Trastorno musculoesquelético postprocedimiento', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    ('M97.9', 'Seudoartrosis y fracaso de la unión de fractura, no especificados', 'Seudoartrosis', 'Traumatología', 'severe', False, False, 'all', 'both'),
    ('M99.9', 'Lesión biomecánica, no especificada', 'Lesión biomecánica', 'Traumatología', 'moderate', False, False, 'all', 'both'),
    
    # Gynecology - Additional
    ('N70.9', 'Salpingitis y ooforitis, no especificada', 'Salpingitis', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N71.9', 'Enfermedad inflamatoria del útero, excepto el cuello, no especificada', 'Enfermedad inflamatoria uterina', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N72', 'Enfermedad inflamatoria del cuello del útero', 'Cervicitis', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N74.9', 'Trastorno inflamatorio de la pelvis femenina en enfermedades clasificadas en otra parte, no especificado', 'Trastorno inflamatorio pélvico', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N75.9', 'Enfermedad de la glándula de Bartholin, no especificada', 'Enfermedad de glándula de Bartholin', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N77.8', 'Ulceración e inflamación vulvovaginal en otras enfermedades clasificadas en otra parte', 'Ulceración vulvovaginal', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N77.9', 'Ulceración e inflamación vulvovaginal en enfermedades clasificadas en otra parte, no especificada', 'Inflamación vulvovaginal', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N78.9', 'Trastorno inflamatorio de la vulva y de la vagina, no especificado', 'Trastorno vulvovaginal', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N81.9', 'Prolapso genital femenino, no especificado', 'Prolapso genital', 'Ginecología', 'moderate', True, False, 'adult', 'female'),
    ('N82.9', 'Fístula que afecta el tracto genital femenino, no especificada', 'Fístula genital', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N83.9', 'Trastorno no inflamatorio del ovario, de la trompa de Falopio y del ligamento ancho, no especificado', 'Trastorno de ovario', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N84.9', 'Pólipo del tracto genital femenino, no especificado', 'Pólipo genital', 'Ginecología', 'mild', False, False, 'adult', 'female'),
    ('N85.9', 'Trastorno no inflamatorio del útero, no especificado', 'Trastorno uterino', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N86', 'Erosión y ectropión del cuello del útero', 'Erosión cervical', 'Ginecología', 'mild', False, False, 'adult', 'female'),
    ('N87.9', 'Displasia del cuello del útero, no especificada', 'Displasia cervical', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N88.9', 'Otros trastornos no inflamatorios del cuello del útero, no especificados', 'Trastorno cervical', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N89.9', 'Trastorno no inflamatorio de la vagina, no especificado', 'Trastorno vaginal', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N90.9', 'Trastorno no inflamatorio de la vulva y del periné, no especificado', 'Trastorno vulvar', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N92.0', 'Menstruación excesiva y frecuente con ciclo regular', 'Menorragia', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N92.1', 'Menstruación excesiva y frecuente con ciclo irregular', 'Menorragia irregular', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N92.2', 'Menstruación excesiva en la pubertad', 'Menorragia puberal', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N92.3', 'Ovulación hemorrágica', 'Sangrado ovulatorio', 'Ginecología', 'mild', False, False, 'adult', 'female'),
    ('N92.4', 'Hemorragia excesiva en la menopausia y la perimenopausia', 'Hemorragia menopáusica', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N92.5', 'Otras menstruaciones irregulares especificadas', 'Menstruación irregular', 'Ginecología', 'mild', False, False, 'adult', 'female'),
    ('N93.9', 'Hemorragia uterina o vaginal anormal, no especificada', 'Hemorragia uterina', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N94.0', 'Dolor en la mitad del ciclo menstrual', 'Dolor intermenstrual', 'Ginecología', 'mild', False, False, 'adult', 'female'),
    ('N94.1', 'Dispareunia', 'Dispareunia', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N94.2', 'Vaginismo', 'Vaginismo', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N94.3', 'Síndrome de tensión premenstrual', 'Síndrome premenstrual', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N94.4', 'Dismenorrea primaria', 'Dismenorrea primaria', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N94.5', 'Dismenorrea secundaria', 'Dismenorrea secundaria', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N94.8', 'Otras afecciones especificadas asociadas con los órganos genitales femeninos y con el ciclo menstrual', 'Otra afección ginecológica', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N94.9', 'Afección no especificada asociada con los órganos genitales femeninos y con el ciclo menstrual', 'Afección ginecológica', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N95.9', 'Trastornos de la menopausia y de la perimenopausia, no especificado', 'Trastorno menopáusico', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('N96', 'Aborto habitual', 'Aborto recurrente', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('N97.9', 'Esterilidad femenina, no especificada', 'Esterilidad femenina', 'Ginecología', 'moderate', True, False, 'adult', 'female'),
    ('N98.9', 'Complicaciones asociadas con la fecundación artificial, no especificadas', 'Complicación de fecundación artificial', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O00.9', 'Embarazo ectópico, no especificado', 'Embarazo ectópico', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O02.9', 'Ovo anormal y mola hidatiforme, no especificados', 'Mola hidatiforme', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O03.9', 'Aborto espontáneo, incompleto, sin complicaciones, no especificado', 'Aborto espontáneo', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O04.9', 'Aborto médico, incompleto, sin complicaciones, no especificado', 'Aborto médico', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O05.9', 'Otro aborto, incompleto, sin complicaciones, no especificado', 'Otro aborto', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O06.9', 'Aborto, no especificado, incompleto, sin complicaciones', 'Aborto incompleto', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O07.9', 'Intento fallido de aborto, sin complicaciones, no especificado', 'Aborto fallido', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O08.9', 'Complicaciones consecutivas a aborto, embarazo ectópico y mola hidatiforme, no especificadas', 'Complicación de aborto', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O10.9', 'Hipertensión preexistente que complica el embarazo, el parto y el puerperio, no especificada', 'Hipertensión en embarazo', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O11', 'Hipertensión preexistente con proteinuria superpuesta', 'Hipertensión con proteinuria', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O12.9', 'Edema y proteinuria gestacionales (inducidos por el embarazo), sin hipertensión, no especificados', 'Proteinuria gestacional', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O13', 'Hipertensión gestacional (inducida por el embarazo) sin proteinuria significativa', 'Hipertensión gestacional', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O14.9', 'Preeclampsia, no especificada', 'Preeclampsia', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O15.9', 'Eclampsia en el embarazo, el parto o el puerperio, no especificada', 'Eclampsia', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O16', 'Hipertensión materna, no especificada', 'Hipertensión materna', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O20.9', 'Hemorragia al inicio del embarazo, no especificada', 'Hemorragia en embarazo temprano', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O21.9', 'Vómitos excesivos en el embarazo, no especificados', 'Hiperémesis gravídica', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O22.9', 'Complicaciones venosas en el embarazo, no especificadas', 'Complicación venosa en embarazo', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O23.9', 'Infección del tracto genitourinario en el embarazo, no especificada', 'Infección urinaria en embarazo', 'Ginecología', 'moderate', False, True, 'adult', 'female'),
    ('O24.9', 'Diabetes mellitus en el embarazo, el parto o el puerperio, no especificada', 'Diabetes gestacional', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O25', 'Desnutrición en el embarazo, el parto o el puerperio', 'Desnutrición en embarazo', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O26.9', 'Atención materna por otra complicación especificada del embarazo, no especificada', 'Complicación del embarazo', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O28.9', 'Hallazgo anormal en el examen antenatal de la madre, no especificado', 'Hallazgo anormal en embarazo', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O29.9', 'Complicaciones de la anestesia administrada durante el embarazo, no especificadas', 'Complicación anestésica en embarazo', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O30.9', 'Embarazo múltiple, no especificado', 'Embarazo múltiple', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O31.9', 'Complicaciones específicas del embarazo múltiple, no especificadas', 'Complicación de embarazo múltiple', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O32.9', 'Atención materna por presentación anormal conocida o sospechada del feto, no especificada', 'Presentación anormal', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O33.9', 'Atención materna por desproporción conocida o sospechada, no especificada', 'Desproporción fetopélvica', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O34.9', 'Atención materna por anormalidad conocida o sospechada de los órganos pélvicos, no especificada', 'Anormalidad pélvica', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O35.9', 'Atención materna por anormalidad y lesión fetales conocidas o sospechadas, no especificada', 'Anormalidad fetal', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O36.9', 'Atención materna por otros problemas fetales conocidos o sospechados, no especificados', 'Problema fetal', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O40.9', 'Polihidramnios, no especificado', 'Polihidramnios', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O41.9', 'Otros trastornos de las membranas y del líquido amniótico, no especificados', 'Trastorno de membranas', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O42.9', 'Ruptura prematura de membranas, no especificada', 'Ruptura prematura de membranas', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O43.9', 'Trastornos de la placenta, no especificados', 'Trastorno placentario', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O44.9', 'Placenta previa, no especificada', 'Placenta previa', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O45.9', 'Desprendimiento prematuro de la placenta, no especificado', 'Desprendimiento de placenta', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O46.9', 'Hemorragia anteparto, no especificada', 'Hemorragia anteparto', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O47.9', 'Falso trabajo de parto, no especificado', 'Falso trabajo de parto', 'Ginecología', 'mild', False, False, 'adult', 'female'),
    ('O48', 'Embarazo prolongado', 'Embarazo prolongado', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O60', 'Parto prematuro', 'Parto prematuro', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O61.9', 'Fallo en la inducción del trabajo de parto, no especificado', 'Fallo en inducción', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O62.9', 'Anormalidades de las contracciones, no especificadas', 'Anormalidad de contracciones', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O63.9', 'Trabajo de parto prolongado, no especificado', 'Trabajo de parto prolongado', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O64.9', 'Obstrucción del trabajo de parto debida a presentación, posición o actitud anormales del feto, no especificada', 'Obstrucción del parto', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O65.9', 'Obstrucción del trabajo de parto debida a anormalidad pélvica materna, no especificada', 'Obstrucción pélvica', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O66.9', 'Otra obstrucción del trabajo de parto, no especificada', 'Otra obstrucción del parto', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O67.9', 'Trabajo de parto y parto complicados por hemorragia intraparto, no especificada', 'Hemorragia intraparto', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O68.9', 'Trabajo de parto y parto complicados por sufrimiento fetal, no especificado', 'Sufrimiento fetal', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O69.9', 'Trabajo de parto y parto complicados por anormalidad del cordón umbilical, no especificada', 'Anormalidad del cordón', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O70.9', 'Desgarro del periné durante el parto, de tercer grado, no especificado', 'Desgarro perineal de tercer grado', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O71.9', 'Otra laceración obstétrica, no especificada', 'Laceración obstétrica', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O72.9', 'Hemorragia postparto, no especificada', 'Hemorragia postparto', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O73.9', 'Retención de la placenta y de las membranas, sin hemorragia, no especificada', 'Retención placentaria', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O74.9', 'Complicaciones de la anestesia durante el trabajo de parto y el parto, no especificadas', 'Complicación anestésica en parto', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O75.9', 'Otras complicaciones del trabajo de parto y del parto, no especificadas', 'Otra complicación del parto', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O80', 'Parto único espontáneo', 'Parto espontáneo', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O81', 'Parto único con forceps y ventosa extractora', 'Parto con forceps', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O82', 'Parto único por cesárea', 'Cesárea', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O83.9', 'Otro parto único asistido, no especificado', 'Parto asistido', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O84.9', 'Parto múltiple, todos espontáneos, no especificado', 'Parto múltiple espontáneo', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O85', 'Sepsis puerperal', 'Sepsis puerperal', 'Ginecología', 'severe', False, True, 'adult', 'female'),
    ('O86.9', 'Otra infección puerperal, no especificada', 'Infección puerperal', 'Ginecología', 'moderate', False, True, 'adult', 'female'),
    ('O87.9', 'Complicaciones venosas en el puerperio, no especificadas', 'Complicación venosa puerperal', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O88.9', 'Embolia obstétrica, no especificada', 'Embolia obstétrica', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O89.9', 'Complicaciones de la anestesia administrada durante el puerperio, no especificadas', 'Complicación anestésica puerperal', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O90.9', 'Complicaciones del puerperio, no clasificadas en otra parte, no especificada', 'Complicación puerperal', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O91.9', 'Infecciones de la mama asociadas con el parto, no especificada', 'Infección mamaria puerperal', 'Ginecología', 'moderate', False, True, 'adult', 'female'),
    ('O92.9', 'Otras anormalidades de la mama y de la lactancia asociadas con el parto, no especificadas', 'Anormalidad mamaria puerperal', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    ('O94', 'Secuelas de complicaciones del embarazo, parto y puerperio', 'Secuela obstétrica', 'Ginecología', 'moderate', True, False, 'adult', 'female'),
    ('O95', 'Muerte obstétrica de causa no especificada', 'Muerte obstétrica', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O96.9', 'Muerte por cualquier causa obstétrica que ocurre más de 42 días pero menos de un año después del parto, no especificada', 'Muerte obstétrica tardía', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O97.9', 'Muerte por secuelas de causas obstétricas directas, no especificada', 'Muerte por secuela obstétrica', 'Ginecología', 'severe', False, False, 'adult', 'female'),
    ('O98.9', 'Enfermedades maternas infecciosas y parasitarias que complican el embarazo, el parto y el puerperio, no especificada', 'Infección materna en embarazo', 'Ginecología', 'moderate', False, True, 'adult', 'female'),
    ('O99.9', 'Otras enfermedades maternas que complican el embarazo, el parto y el puerperio, no especificada', 'Enfermedad materna en embarazo', 'Ginecología', 'moderate', False, False, 'adult', 'female'),
    
    # Urology - Additional
    ('N20.9', 'Cálculo del tracto urinario, no especificado', 'Cálculo urinario', 'Urología', 'moderate', False, False, 'all', 'both'),
    ('N21.9', 'Cálculo del tracto urinario inferior, no especificado', 'Cálculo urinario inferior', 'Urología', 'moderate', False, False, 'all', 'both'),
    ('N25.9', 'Trastorno resultante de función renal tubular alterada, no especificado', 'Trastorno renal tubular', 'Nefrología', 'moderate', True, False, 'all', 'both'),
    ('N26.9', 'Riñón contraído, no especificado', 'Riñón contraído', 'Nefrología', 'severe', True, False, 'all', 'both'),
    ('N28.9', 'Otros trastornos del riñón y del uréter, no especificados', 'Trastorno renal', 'Nefrología', 'moderate', False, False, 'all', 'both'),
    ('N29.9', 'Otros trastornos del riñón y del uréter en enfermedades clasificadas en otra parte, no especificados', 'Trastorno renal secundario', 'Nefrología', 'moderate', False, False, 'all', 'both'),
    ('N30.9', 'Cistitis, no especificada', 'Cistitis', 'Urología', 'moderate', False, True, 'all', 'both'),
    ('N32.9', 'Trastorno de la vejiga, no especificado', 'Trastorno vesical', 'Urología', 'moderate', False, False, 'all', 'both'),
    ('N34.9', 'Uretritis y síndrome uretral, no especificados', 'Uretritis', 'Urología', 'moderate', False, True, 'all', 'both'),
    ('N35.9', 'Estenosis uretral, no especificada', 'Estenosis uretral', 'Urología', 'moderate', True, False, 'all', 'both'),
    ('N36.9', 'Otro trastorno de la uretra, no especificado', 'Trastorno uretral', 'Urología', 'moderate', False, False, 'all', 'both'),
    ('N39.9', 'Trastorno del sistema urinario, no especificado', 'Trastorno urinario', 'Urología', 'moderate', False, False, 'all', 'both'),
    ('N40.9', 'Hiperplasia de la próstata, no especificada', 'Hiperplasia prostática', 'Urología', 'moderate', True, False, 'adult', 'male'),
    ('N41.9', 'Enfermedad inflamatoria de la próstata, no especificada', 'Prostatitis', 'Urología', 'moderate', False, False, 'adult', 'male'),
    ('N42.9', 'Otros trastornos de la próstata, no especificados', 'Trastorno prostático', 'Urología', 'moderate', False, False, 'adult', 'male'),
    ('N43.9', 'Hidrocele y espermatocele, no especificados', 'Hidrocele', 'Urología', 'mild', False, False, 'all', 'male'),
    ('N44.9', 'Torsión del testículo', 'Torsión testicular', 'Urología', 'severe', False, False, 'all', 'male'),
    ('N45.9', 'Orquitis y epididimitis, no especificadas', 'Orquitis', 'Urología', 'moderate', False, True, 'all', 'male'),
    ('N46.9', 'Esterilidad masculina, no especificada', 'Esterilidad masculina', 'Urología', 'moderate', True, False, 'adult', 'male'),
    ('N47', 'Fimosis, parafimosis y adherencias del prepucio y pene', 'Fimosis', 'Urología', 'mild', True, False, 'all', 'male'),
    ('N48.9', 'Otros trastornos del pene, no especificados', 'Trastorno del pene', 'Urología', 'moderate', False, False, 'all', 'male'),
    ('N49.9', 'Trastornos inflamatorios de órganos genitales masculinos, no especificados', 'Trastorno genital masculino', 'Urología', 'moderate', False, True, 'all', 'male'),
    ('N50.9', 'Otros trastornos de órganos genitales masculinos, no especificados', 'Trastorno genital masculino', 'Urología', 'moderate', False, False, 'all', 'male'),
    ('N51.9', 'Trastornos de los órganos genitales masculinos en enfermedades clasificadas en otra parte, no especificados', 'Trastorno genital masculino secundario', 'Urología', 'moderate', False, False, 'all', 'male'),
    
    # Dermatology - Additional
    ('L00', 'Síndrome de piel escaldada estafilocócica', 'Síndrome de piel escaldada', 'Dermatología', 'severe', False, True, 'pediatric', 'both'),
    ('L01.9', 'Impetigo, no especificado', 'Impetigo', 'Dermatología', 'moderate', False, True, 'all', 'both'),
    ('L02.9', 'Absceso cutáneo, furúnculo y ántrax, no especificados', 'Furúnculo', 'Dermatología', 'moderate', False, True, 'all', 'both'),
    ('L03.9', 'Celulitis, no especificada', 'Celulitis', 'Dermatología', 'moderate', False, True, 'all', 'both'),
    ('L04.9', 'Linfadenitis aguda, no especificada', 'Linfadenitis aguda', 'Dermatología', 'moderate', False, True, 'all', 'both'),
    ('L05.9', 'Quiste pilonidal, no especificado', 'Quiste pilonidal', 'Dermatología', 'moderate', True, False, 'all', 'both'),
    ('L08.9', 'Infección localizada de la piel y del tejido subcutáneo, no especificada', 'Infección cutánea', 'Dermatología', 'moderate', False, True, 'all', 'both'),
    ('L20.9', 'Dermatitis atópica, no especificada', 'Dermatitis atópica', 'Dermatología', 'moderate', True, False, 'all', 'both'),
    ('L21.9', 'Seborrea, no especificada', 'Seborrea', 'Dermatología', 'mild', True, False, 'all', 'both'),
    ('L22', 'Dermatitis del pañal', 'Dermatitis del pañal', 'Dermatología', 'mild', False, False, 'pediatric', 'both'),
    ('L23.9', 'Dermatitis alérgica de contacto, no especificada', 'Dermatitis de contacto', 'Dermatología', 'moderate', True, False, 'all', 'both'),
    ('L24.9', 'Dermatitis de contacto por irritantes, no especificada', 'Dermatitis irritativa', 'Dermatología', 'moderate', False, False, 'all', 'both'),
    ('L25.9', 'Dermatitis de contacto, no especificada', 'Dermatitis de contacto', 'Dermatología', 'moderate', False, False, 'all', 'both'),
    ('L26', 'Dermatitis exfoliativa', 'Dermatitis exfoliativa', 'Dermatología', 'severe', False, False, 'all', 'both'),
    ('L27.9', 'Dermatitis debida a sustancias ingeridas, no especificada', 'Dermatitis por ingesta', 'Dermatología', 'moderate', False, False, 'all', 'both'),
    ('L28.9', 'Liquen simple crónico y prurigo, no especificados', 'Liquen simple', 'Dermatología', 'moderate', True, False, 'all', 'both'),
    ('L29.9', 'Prurito, no especificado', 'Prurito', 'Dermatología', 'mild', False, False, 'all', 'both'),
    ('L30.9', 'Otras dermatitis, no especificadas', 'Otra dermatitis', 'Dermatología', 'moderate', False, False, 'all', 'both'),
    ('L40.9', 'Psoriasis, no especificada', 'Psoriasis', 'Dermatología', 'moderate', True, False, 'all', 'both'),
    ('L50.9', 'Urticaria, no especificada', 'Urticaria', 'Dermatología', 'moderate', False, False, 'all', 'both'),
    ('L53.9', 'Otras afecciones eritematosas, no especificadas', 'Afección eritematosa', 'Dermatología', 'moderate', False, False, 'all', 'both'),
    ('L70.9', 'Acné, no especificado', 'Acné', 'Dermatología', 'mild', True, False, 'all', 'both'),
    ('L71.9', 'Rosácea, no especificada', 'Rosácea', 'Dermatología', 'moderate', True, False, 'adult', 'both'),
    ('L72.9', 'Quiste folicular de la piel y del tejido subcutáneo, no especificado', 'Quiste folicular', 'Dermatología', 'mild', False, False, 'all', 'both'),
    ('L73.9', 'Otras afecciones foliculares, no especificadas', 'Afección folicular', 'Dermatología', 'mild', False, False, 'all', 'both'),
    ('L74.9', 'Trastornos de las glándulas sudoríparas ecrinas, no especificados', 'Trastorno de glándulas sudoríparas', 'Dermatología', 'mild', False, False, 'all', 'both'),
    ('L75.9', 'Trastornos de las glándulas apocrinas sudoríparas, no especificados', 'Trastorno de glándulas apocrinas', 'Dermatología', 'mild', False, False, 'all', 'both'),
    ('L80', 'Vitiligo', 'Vitiligo', 'Dermatología', 'mild', True, False, 'all', 'both'),
    ('L81.9', 'Otros trastornos de la pigmentación, no especificados', 'Trastorno de pigmentación', 'Dermatología', 'mild', False, False, 'all', 'both'),
    ('L82', 'Queratosis seborreica', 'Queratosis seborreica', 'Dermatología', 'mild', False, False, 'adult', 'both'),
    ('L84', 'Callos y callosidades', 'Callos', 'Dermatología', 'mild', False, False, 'all', 'both'),
    ('L85.9', 'Otros trastornos de la epidermis engrosada, no especificados', 'Trastorno de epidermis', 'Dermatología', 'mild', False, False, 'all', 'both'),
    ('L87.9', 'Trastornos de la eliminación transepidérmica, no especificados', 'Trastorno de eliminación', 'Dermatología', 'moderate', True, False, 'all', 'both'),
    ('L89.9', 'Úlcera de decúbito, no especificada', 'Úlcera por presión', 'Dermatología', 'moderate', False, False, 'all', 'both'),
    ('L90.9', 'Atrofias cutáneas, no especificadas', 'Atrofia cutánea', 'Dermatología', 'moderate', True, False, 'all', 'both'),
    ('L91.9', 'Trastornos hipertróficos de la piel, no especificados', 'Trastorno hipertrófico', 'Dermatología', 'mild', False, False, 'all', 'both'),
    ('L92.9', 'Trastornos granulomatosos de la piel y del tejido subcutáneo, no especificados', 'Granuloma cutáneo', 'Dermatología', 'moderate', False, False, 'all', 'both'),
    ('L93.9', 'Lupus eritematoso, no especificado', 'Lupus eritematoso', 'Dermatología', 'moderate', True, False, 'all', 'both'),
    ('L94.9', 'Otros trastornos localizados del tejido conectivo, no especificados', 'Trastorno del tejido conectivo', 'Dermatología', 'moderate', True, False, 'all', 'both'),
    ('L95.9', 'Vasculitis limitada a la piel, no especificada', 'Vasculitis cutánea', 'Dermatología', 'moderate', True, False, 'all', 'both'),
    ('L98.9', 'Trastorno de la piel y del tejido subcutáneo, no especificado', 'Trastorno cutáneo', 'Dermatología', 'moderate', False, False, 'all', 'both'),
    ('L99', 'Otros trastornos de la piel y del tejido subcutáneo en enfermedades clasificadas en otra parte', 'Trastorno cutáneo secundario', 'Dermatología', 'moderate', False, False, 'all', 'both'),
]

def generate_sql():
    """Generate SQL INSERT statements for additional diagnoses"""
    sql_lines = [
        "-- ============================================================================",
        "-- MIGRATION: Preload Additional Common Medical Diagnoses from Mexico",
        "-- Description: Adds common medical diagnoses from Mexico",
        "--              All diagnoses are set with created_by = 0 (system)",
        "--              Only includes code and name (required fields by law)",
        "-- Author: CORTEX Medical Records System",
        "-- Date: 2025-01-22",
        "-- Compliance: NOM-004-SSA3-2012, NOM-024-SSA3-2012 - CIE-10 catalog",
        "-- ============================================================================",
        "",
        "INSERT INTO diagnosis_catalog (code, name, is_active, created_by, created_at, updated_at)",
        "VALUES"
    ]
    
    # Generate VALUES for each diagnosis
    values = []
    for item in ADDITIONAL_DIAGNOSES:
        # Handle both old format (9 fields) and new format (2 fields)
        if len(item) == 2:
            code, name = item
        else:
            # Extract only code and name from old format
            code = item[0]
            name = item[1]
        
        # Escape single quotes in name
        name_escaped = name.replace("'", "''")
        values.append(
            f"('{code}', '{name_escaped}', true, 0, NOW(), NOW())"
        )
    
    # Join values with commas
    sql_lines.append(",\n".join(values))
    sql_lines.append("")
    sql_lines.append("ON CONFLICT (code) DO UPDATE SET")
    sql_lines.append("    name = EXCLUDED.name,")
    sql_lines.append("    is_active = EXCLUDED.is_active,")
    sql_lines.append("    created_by = 0,")
    sql_lines.append("    updated_at = NOW();")
    sql_lines.append("")
    sql_lines.append("-- Verify total diagnoses count")
    sql_lines.append("SELECT COUNT(*) as total_diagnoses")
    sql_lines.append("FROM diagnosis_catalog")
    sql_lines.append("WHERE created_by = 0 AND is_active = true;")
    
    return "\n".join(sql_lines)

if __name__ == "__main__":
    sql = generate_sql()
    print(sql)

