"""descripción

Revision ID: d5be39ff35bc
Revises: 
Create Date: 2025-11-26 03:22:55.566884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5be39ff35bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop views that depend on data_retention_logs first
    op.execute('DROP VIEW IF EXISTS v_data_retention_expiring CASCADE')
    op.execute('DROP VIEW IF EXISTS v_data_retention_stats CASCADE')
    # Now we can drop the table
    op.drop_table('data_retention_logs')
    op.drop_constraint('appointment_reminders_appointment_id_reminder_number_key', 'appointment_reminders', type_='unique')
    op.drop_index('idx_appointment_reminders_appointment_id', table_name='appointment_reminders', if_exists=True)
    op.drop_index('idx_appointment_reminders_appointment_status', table_name='appointment_reminders', postgresql_where='((enabled = true) AND (sent = false))', if_exists=True)
    op.drop_index('idx_appointment_reminders_enabled_sent', table_name='appointment_reminders', postgresql_where='((enabled = true) AND (sent = false))', if_exists=True)
    op.drop_index('idx_appointment_reminders_whatsapp_message_id', table_name='appointment_reminders', if_exists=True)
    op.create_unique_constraint('unique_appointment_reminder_number', 'appointment_reminders', ['appointment_id', 'reminder_number'])
    op.drop_table_comment(
        'appointment_reminders',
        existing_comment='Stores up to 3 automatic reminders per appointment. Each reminder can be enabled/disabled independently and has a custom offset_minutes (time before appointment).',
        schema=None
    )
    op.alter_column('appointments', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('idx_appointments_appointment_date', table_name='appointments')
    op.drop_index('idx_appointments_doctor_id', table_name='appointments')
    op.drop_index('idx_appointments_patient_doctor', table_name='appointments')
    op.drop_index('idx_appointments_patient_id', table_name='appointments')
    op.create_foreign_key(None, 'appointments', 'appointment_types', ['appointment_type_id'], ['id'])
    op.create_foreign_key(None, 'appointments', 'offices', ['office_id'], ['id'])
    op.drop_table_comment(
        'appointments',
        existing_comment='Citas médicas',
        schema=None
    )
    op.drop_column('appointments', 'reason')
    op.drop_column('appointments', 'priority')
    op.drop_column('appointments', 'duration_minutes')
    op.drop_column('appointments', 'notes')
    op.drop_table_comment(
        'arco_requests',
        existing_comment='Solicitudes ARCO (LFPDPPP)',
        schema=None
    )
    op.drop_index('idx_audit_log_timestamp', table_name='audit_log')
    op.drop_index('idx_audit_log_timestamp_user', table_name='audit_log')
    op.drop_index('idx_audit_log_user_id', table_name='audit_log')
    op.drop_table_comment(
        'audit_log',
        existing_comment='Log de auditoría del sistema',
        schema=None
    )
    op.alter_column('clinical_studies', 'study_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('clinical_studies', 'study_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('clinical_studies', 'ordered_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('clinical_studies', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'ordered'::character varying"))
    op.alter_column('clinical_studies', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index('idx_clinical_studies_ordered_date', table_name='clinical_studies')
    op.drop_index('idx_clinical_studies_patient_doctor', table_name='clinical_studies')
    op.drop_index('idx_clinical_studies_patient_id', table_name='clinical_studies')
    op.create_index(op.f('ix_clinical_studies_id'), 'clinical_studies', ['id'], unique=False)
    op.drop_constraint('clinical_studies_consultation_id_fkey', 'clinical_studies', type_='foreignkey')
    op.create_foreign_key(None, 'clinical_studies', 'medical_records', ['consultation_id'], ['id'])
    op.drop_table_comment(
        'clinical_studies',
        existing_comment='Estudios clínicos realizados',
        schema=None
    )
    op.alter_column('consultation_prescriptions', 'consultation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('consultation_prescriptions', 'medication_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('consultation_prescriptions', 'dosage',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('consultation_prescriptions', 'frequency',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('consultation_prescriptions', 'duration',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.drop_constraint('consultation_prescriptions_consultation_id_fkey', 'consultation_prescriptions', type_='foreignkey')
    op.create_foreign_key(None, 'consultation_prescriptions', 'medical_records', ['consultation_id'], ['id'])
    op.alter_column('consultation_vital_signs', 'consultation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('consultation_vital_signs', 'vital_sign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('consultation_vital_signs_consultation_id_fkey', 'consultation_vital_signs', type_='foreignkey')
    op.create_foreign_key(None, 'consultation_vital_signs', 'medical_records', ['consultation_id'], ['id'])
    op.drop_table_comment(
        'consultation_vital_signs',
        existing_comment='Signos vitales por consulta',
        schema=None
    )
    op.drop_table_comment(
        'countries',
        existing_comment='Catálogo de países del mundo',
        schema=None
    )
    op.alter_column('diagnosis_catalog', 'code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               nullable=False)
    op.alter_column('diagnosis_catalog', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('diagnosis_catalog', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('diagnosis_catalog', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('diagnosis_catalog_code_key', 'diagnosis_catalog', type_='unique')
    op.drop_index('idx_diagnosis_catalog_code', table_name='diagnosis_catalog')
    op.drop_index('idx_diagnosis_catalog_created_by', table_name='diagnosis_catalog')
    op.create_index(op.f('ix_diagnosis_catalog_code'), 'diagnosis_catalog', ['code'], unique=True)
    op.create_index(op.f('ix_diagnosis_catalog_created_by'), 'diagnosis_catalog', ['created_by'], unique=False)
    op.create_index(op.f('ix_diagnosis_catalog_id'), 'diagnosis_catalog', ['id'], unique=False)
    op.drop_table_comment(
        'diagnosis_catalog',
        existing_comment='Catálogo de diagnósticos médicos',
        schema=None
    )
    op.drop_index('idx_document_folio_sequences_doctor_type', table_name='document_folio_sequences')
    op.drop_constraint('document_folio_sequences_doctor_id_fkey', 'document_folio_sequences', type_='foreignkey')
    op.create_foreign_key(None, 'document_folio_sequences', 'persons', ['doctor_id'], ['id'])
    op.drop_index('idx_document_folios_doctor_type_number', table_name='document_folios')
    op.drop_index('idx_document_folios_unique_consultation', table_name='document_folios')
    op.drop_constraint('document_folios_doctor_id_fkey', 'document_folios', type_='foreignkey')
    op.drop_constraint('document_folios_consultation_id_fkey', 'document_folios', type_='foreignkey')
    op.create_foreign_key(None, 'document_folios', 'medical_records', ['consultation_id'], ['id'])
    op.create_foreign_key(None, 'document_folios', 'persons', ['doctor_id'], ['id'])
    op.drop_constraint('documents_name_document_type_id_key', 'documents', type_='unique')
    op.drop_table_comment(
        'emergency_relationships',
        existing_comment='Relaciones familiares para contactos de emergencia',
        schema=None
    )
    op.alter_column('google_calendar_event_mappings', 'appointment_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID de la cita en el sistema',
               existing_nullable=False)
    op.alter_column('google_calendar_event_mappings', 'google_event_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='ID del evento en Google Calendar',
               existing_nullable=False)
    op.alter_column('google_calendar_event_mappings', 'doctor_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID del doctor propietario del evento',
               existing_nullable=False)
    op.drop_index('idx_google_event_mappings_appointment_id', table_name='google_calendar_event_mappings')
    op.drop_index('idx_google_event_mappings_doctor_id', table_name='google_calendar_event_mappings')
    op.drop_index('idx_google_event_mappings_google_event_id', table_name='google_calendar_event_mappings')
    op.drop_table_comment(
        'google_calendar_event_mappings',
        existing_comment='Mapea citas del sistema con eventos de Google Calendar',
        schema=None
    )
    op.alter_column('google_calendar_tokens', 'doctor_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID del doctor que conectó su Google Calendar',
               existing_nullable=False)
    op.alter_column('google_calendar_tokens', 'access_token',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Token de acceso de OAuth (encriptar en producción)',
               existing_nullable=False)
    op.alter_column('google_calendar_tokens', 'refresh_token',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Token de refresco para renovar access_token',
               existing_nullable=True)
    op.alter_column('google_calendar_tokens', 'token_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Fecha de expiración del access_token',
               existing_nullable=True)
    op.alter_column('google_calendar_tokens', 'calendar_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='ID del calendario de Google (default: primary)',
               existing_nullable=True,
               existing_server_default=sa.text("'primary'::character varying"))
    op.alter_column('google_calendar_tokens', 'sync_enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indica si la sincronización está habilitada',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index('idx_google_calendar_tokens_channel_id', table_name='google_calendar_tokens')
    op.drop_index('idx_google_calendar_tokens_doctor_id', table_name='google_calendar_tokens')
    op.drop_index('idx_google_calendar_tokens_resource_id', table_name='google_calendar_tokens')
    op.drop_index('idx_google_calendar_tokens_sync_enabled', table_name='google_calendar_tokens')
    op.drop_table_comment(
        'google_calendar_tokens',
        existing_comment='Almacena tokens OAuth de Google Calendar por doctor',
        schema=None
    )
    op.drop_column('google_calendar_tokens', 'resource_id')
    op.drop_column('google_calendar_tokens', 'watch_expiration')
    op.drop_column('google_calendar_tokens', 'channel_id')
    op.drop_index('idx_medical_records_anonymized', table_name='medical_records')
    op.drop_index('idx_medical_records_archived', table_name='medical_records')
    op.drop_index('idx_medical_records_consultation_date', table_name='medical_records')
    op.drop_index('idx_medical_records_doctor_id', table_name='medical_records')
    op.drop_index('idx_medical_records_legal_hold', table_name='medical_records', postgresql_where='(legal_hold = true)')
    op.drop_index('idx_medical_records_patient_doctor', table_name='medical_records')
    op.drop_index('idx_medical_records_patient_document', table_name='medical_records')
    op.drop_index('idx_medical_records_patient_id', table_name='medical_records')
    op.drop_index('idx_medical_records_retention_end', table_name='medical_records', postgresql_where='((retention_end_date IS NOT NULL) AND (is_anonymized = false))')
    op.drop_table_comment(
        'medical_records',
        existing_comment='Historias clínicas/consultas médicas',
        schema=None
    )
    op.drop_column('medical_records', 'retention_end_date')
    op.drop_column('medical_records', 'is_archived')
    op.drop_column('medical_records', 'anonymization_date')
    op.drop_column('medical_records', 'archived_date')
    op.drop_column('medical_records', 'is_anonymized')
    op.drop_column('medical_records', 'legal_hold')
    op.drop_column('medical_records', 'legal_hold_reason')
    op.alter_column('medications', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    # Before creating FK, update any created_by=0 to a valid person_id
    # Find the first doctor (person_type='doctor') and use their ID, or set to NULL if no doctors exist
    op.execute("""
        UPDATE medications 
        SET created_by = (
            SELECT id FROM persons 
            WHERE person_type = 'doctor' 
            ORDER BY id 
            LIMIT 1
        )
        WHERE created_by = 0 AND EXISTS (SELECT 1 FROM persons WHERE person_type = 'doctor')
    """)
    # If no doctors exist, set to NULL
    op.execute("UPDATE medications SET created_by = NULL WHERE created_by = 0")
    # Make column nullable temporarily to allow FK creation
    op.alter_column('medications', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=None)
    # Create FK (allows NULL values)
    op.create_foreign_key(None, 'medications', 'persons', ['created_by'], ['id'])
    # Now make it NOT NULL if we want (but this might fail if there are still NULLs)
    # For now, we'll leave it nullable to match the constraint that allows system-created medications
    op.drop_table_comment(
        'medications',
        existing_comment='Catálogo de medicamentos',
        schema=None
    )
    op.drop_index('idx_offices_doctor_id', table_name='offices')
    op.drop_index('idx_offices_is_active', table_name='offices')
    op.drop_index('idx_person_documents_document_id', table_name='person_documents')
    op.drop_index('idx_person_documents_person_id', table_name='person_documents')
    op.drop_index('idx_person_documents_value', table_name='person_documents')
    op.drop_constraint('person_documents_person_id_document_id_key', 'person_documents', type_='unique')
    op.alter_column('persons', 'title',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Professional title for doctors (Dr., Dra., etc.) - kept separate',
               existing_nullable=True)
    op.alter_column('persons', 'name',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='Full name of the person (replaces first_name, paternal_surname, maternal_surname)',
               existing_nullable=False)
    op.alter_column('persons', 'gender',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Optional field. Can be NULL when creating patients from appointment dialogs or when patient prefers not to specify.',
               existing_nullable=True)
    op.drop_index('idx_persons_email', table_name='persons')
    op.drop_index('idx_persons_person_type', table_name='persons')
    op.drop_constraint('persons_office_state_id_fkey', 'persons', type_='foreignkey')
    op.drop_table_comment(
        'persons',
        existing_comment='Tabla unificada de doctores, pacientes y administradores',
        schema=None
    )
    op.drop_column('persons', 'office_postal_code')
    op.drop_column('persons', 'office_timezone')
    op.drop_column('persons', 'office_state_id')
    op.drop_column('persons', 'office_address')
    op.drop_column('persons', 'office_city')
    op.drop_column('persons', 'office_phone')
    op.drop_index('idx_privacy_consents_anonymized', table_name='privacy_consents')
    op.drop_index('idx_privacy_consents_deletion_scheduled', table_name='privacy_consents', postgresql_where='((deletion_scheduled_date IS NOT NULL) AND (is_anonymized = false))')
    op.drop_table_comment(
        'privacy_consents',
        existing_comment='Consentimientos de privacidad',
        schema=None
    )
    op.drop_column('privacy_consents', 'data_retention_years')
    op.drop_column('privacy_consents', 'anonymization_date')
    op.drop_column('privacy_consents', 'anonymization_reason')
    op.drop_column('privacy_consents', 'deletion_scheduled_date')
    op.drop_column('privacy_consents', 'is_anonymized')
    op.create_unique_constraint(None, 'privacy_notices', ['version'])
    op.drop_table_comment(
        'privacy_notices',
        existing_comment='Avisos de privacidad',
        schema=None
    )
    op.add_column('schedule_templates', sa.Column('consultation_duration', sa.Integer(), nullable=True))
    op.add_column('schedule_templates', sa.Column('break_duration', sa.Integer(), nullable=True))
    op.add_column('schedule_templates', sa.Column('lunch_start', sa.Time(), nullable=True))
    op.add_column('schedule_templates', sa.Column('lunch_end', sa.Time(), nullable=True))
    # Before making office_id NOT NULL, update any NULL values
    # Find the first office for each doctor, or create a default office
    op.execute("""
        UPDATE schedule_templates st
        SET office_id = (
            SELECT o.id 
            FROM offices o 
            WHERE o.doctor_id = st.doctor_id 
            ORDER BY o.id 
            LIMIT 1
        )
        WHERE st.office_id IS NULL AND st.doctor_id IS NOT NULL
    """)
    # If still NULL (no offices for doctor), delete those records or set to a default
    # For safety, we'll delete schedule templates without office_id
    op.execute("DELETE FROM schedule_templates WHERE office_id IS NULL")
    op.alter_column('schedule_templates', 'office_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_schedule_templates_id'), 'schedule_templates', ['id'], unique=False)
    op.drop_constraint('schedule_templates_office_id_fkey', 'schedule_templates', type_='foreignkey')
    op.drop_constraint('schedule_templates_doctor_id_fkey', 'schedule_templates', type_='foreignkey')
    op.create_foreign_key(None, 'schedule_templates', 'persons', ['doctor_id'], ['id'])
    op.create_foreign_key(None, 'schedule_templates', 'offices', ['office_id'], ['id'])
    op.drop_column('schedule_templates', 'time_blocks')
    op.drop_constraint('states_country_id_fkey', 'states', type_='foreignkey')
    op.create_foreign_key(None, 'states', 'countries', ['country_id'], ['id'])
    op.drop_table_comment(
        'states',
        existing_comment='Catálogo de estados/provincias por país',
        schema=None
    )
    op.alter_column('study_catalog', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_study_catalog_id'), 'study_catalog', ['id'], unique=False)
    op.drop_table_comment(
        'study_catalog',
        existing_comment='Catálogo de estudios clínicos disponibles',
        schema=None
    )
    op.create_index(op.f('ix_study_categories_id'), 'study_categories', ['id'], unique=False)
    op.drop_table_comment(
        'study_categories',
        existing_comment='Categorías de estudios clínicos',
        schema=None
    )
    op.drop_table_comment(
        'vital_signs',
        existing_comment='Catálogo de signos vitales',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'vital_signs',
        'Catálogo de signos vitales',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'study_categories',
        'Categorías de estudios clínicos',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_study_categories_id'), table_name='study_categories')
    op.create_table_comment(
        'study_catalog',
        'Catálogo de estudios clínicos disponibles',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_study_catalog_id'), table_name='study_catalog')
    op.alter_column('study_catalog', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table_comment(
        'states',
        'Catálogo de estados/provincias por país',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'states', type_='foreignkey')
    op.create_foreign_key('states_country_id_fkey', 'states', 'countries', ['country_id'], ['id'], ondelete='CASCADE')
    op.add_column('schedule_templates', sa.Column('time_blocks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'schedule_templates', type_='foreignkey')
    op.drop_constraint(None, 'schedule_templates', type_='foreignkey')
    op.create_foreign_key('schedule_templates_doctor_id_fkey', 'schedule_templates', 'persons', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('schedule_templates_office_id_fkey', 'schedule_templates', 'offices', ['office_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_schedule_templates_id'), table_name='schedule_templates')
    op.alter_column('schedule_templates', 'office_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('schedule_templates', 'lunch_end')
    op.drop_column('schedule_templates', 'lunch_start')
    op.drop_column('schedule_templates', 'break_duration')
    op.drop_column('schedule_templates', 'consultation_duration')
    op.create_table_comment(
        'privacy_notices',
        'Avisos de privacidad',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'privacy_notices', type_='unique')
    op.add_column('privacy_consents', sa.Column('is_anonymized', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True, comment='Whether the consent data has been anonymized'))
    op.add_column('privacy_consents', sa.Column('deletion_scheduled_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Scheduled date for data deletion after retention period'))
    op.add_column('privacy_consents', sa.Column('anonymization_reason', sa.TEXT(), autoincrement=False, nullable=True, comment='Reason for anonymization (retention_expired, patient_request, etc)'))
    op.add_column('privacy_consents', sa.Column('anonymization_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Date when data was anonymized'))
    op.add_column('privacy_consents', sa.Column('data_retention_years', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=True, comment='Years to retain personal data (default: 5 years per NOM-004)'))
    op.create_table_comment(
        'privacy_consents',
        'Consentimientos de privacidad',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_privacy_consents_deletion_scheduled', 'privacy_consents', ['deletion_scheduled_date'], unique=False, postgresql_where='((deletion_scheduled_date IS NOT NULL) AND (is_anonymized = false))')
    op.create_index('idx_privacy_consents_anonymized', 'privacy_consents', ['is_anonymized', 'anonymization_date'], unique=False)
    op.add_column('persons', sa.Column('office_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('persons', sa.Column('office_city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('persons', sa.Column('office_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('persons', sa.Column('office_state_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('persons', sa.Column('office_timezone', sa.VARCHAR(length=50), server_default=sa.text("'America/Mexico_City'::character varying"), autoincrement=False, nullable=True))
    op.add_column('persons', sa.Column('office_postal_code', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.create_table_comment(
        'persons',
        'Tabla unificada de doctores, pacientes y administradores',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key('persons_office_state_id_fkey', 'persons', 'states', ['office_state_id'], ['id'])
    op.create_index('idx_persons_person_type', 'persons', ['person_type'], unique=False)
    op.create_index('idx_persons_email', 'persons', ['email'], unique=False)
    op.alter_column('persons', 'gender',
               existing_type=sa.VARCHAR(length=20),
               comment='Optional field. Can be NULL when creating patients from appointment dialogs or when patient prefers not to specify.',
               existing_nullable=True)
    op.alter_column('persons', 'name',
               existing_type=sa.VARCHAR(length=300),
               comment='Full name of the person (replaces first_name, paternal_surname, maternal_surname)',
               existing_nullable=False)
    op.alter_column('persons', 'title',
               existing_type=sa.VARCHAR(length=10),
               comment='Professional title for doctors (Dr., Dra., etc.) - kept separate',
               existing_nullable=True)
    op.create_unique_constraint('person_documents_person_id_document_id_key', 'person_documents', ['person_id', 'document_id'])
    op.create_index('idx_person_documents_value', 'person_documents', ['document_value'], unique=False)
    op.create_index('idx_person_documents_person_id', 'person_documents', ['person_id'], unique=False)
    op.create_index('idx_person_documents_document_id', 'person_documents', ['document_id'], unique=False)
    op.create_index('idx_offices_is_active', 'offices', ['is_active'], unique=False)
    op.create_index('idx_offices_doctor_id', 'offices', ['doctor_id'], unique=False)
    op.create_table_comment(
        'medications',
        'Catálogo de medicamentos',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'medications', type_='foreignkey')
    op.alter_column('medications', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('medications', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.add_column('medical_records', sa.Column('legal_hold_reason', sa.TEXT(), autoincrement=False, nullable=True, comment='Reason for legal hold'))
    op.add_column('medical_records', sa.Column('legal_hold', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True, comment='Prevents deletion if under legal investigation'))
    op.add_column('medical_records', sa.Column('is_anonymized', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True, comment='Whether the record has been anonymized'))
    op.add_column('medical_records', sa.Column('archived_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Date when record was archived'))
    op.add_column('medical_records', sa.Column('anonymization_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Date when record was anonymized'))
    op.add_column('medical_records', sa.Column('is_archived', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True, comment='Whether the record has been moved to archive storage'))
    op.add_column('medical_records', sa.Column('retention_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Date when record retention period ends (5 years from last consultation)'))
    op.create_table_comment(
        'medical_records',
        'Historias clínicas/consultas médicas',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_medical_records_retention_end', 'medical_records', ['retention_end_date'], unique=False, postgresql_where='((retention_end_date IS NOT NULL) AND (is_anonymized = false))')
    op.create_index('idx_medical_records_patient_id', 'medical_records', ['patient_id'], unique=False)
    op.create_index('idx_medical_records_patient_document', 'medical_records', ['patient_document_id'], unique=False)
    op.create_index('idx_medical_records_patient_doctor', 'medical_records', ['patient_id', 'doctor_id'], unique=False)
    op.create_index('idx_medical_records_legal_hold', 'medical_records', ['legal_hold'], unique=False, postgresql_where='(legal_hold = true)')
    op.create_index('idx_medical_records_doctor_id', 'medical_records', ['doctor_id'], unique=False)
    op.create_index('idx_medical_records_consultation_date', 'medical_records', ['consultation_date'], unique=False)
    op.create_index('idx_medical_records_archived', 'medical_records', ['is_archived', 'archived_date'], unique=False)
    op.create_index('idx_medical_records_anonymized', 'medical_records', ['is_anonymized', 'anonymization_date'], unique=False)
    op.add_column('google_calendar_tokens', sa.Column('channel_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='ID del canal de webhook de Google Calendar'))
    op.add_column('google_calendar_tokens', sa.Column('watch_expiration', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Fecha de expiración de la suscripción (max 7 días)'))
    op.add_column('google_calendar_tokens', sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='ID del recurso de la suscripción (watch)'))
    op.create_table_comment(
        'google_calendar_tokens',
        'Almacena tokens OAuth de Google Calendar por doctor',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_google_calendar_tokens_sync_enabled', 'google_calendar_tokens', ['sync_enabled'], unique=False)
    op.create_index('idx_google_calendar_tokens_resource_id', 'google_calendar_tokens', ['resource_id'], unique=False)
    op.create_index('idx_google_calendar_tokens_doctor_id', 'google_calendar_tokens', ['doctor_id'], unique=False)
    op.create_index('idx_google_calendar_tokens_channel_id', 'google_calendar_tokens', ['channel_id'], unique=False)
    op.alter_column('google_calendar_tokens', 'sync_enabled',
               existing_type=sa.BOOLEAN(),
               comment='Indica si la sincronización está habilitada',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('google_calendar_tokens', 'calendar_id',
               existing_type=sa.VARCHAR(length=255),
               comment='ID del calendario de Google (default: primary)',
               existing_nullable=True,
               existing_server_default=sa.text("'primary'::character varying"))
    op.alter_column('google_calendar_tokens', 'token_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha de expiración del access_token',
               existing_nullable=True)
    op.alter_column('google_calendar_tokens', 'refresh_token',
               existing_type=sa.TEXT(),
               comment='Token de refresco para renovar access_token',
               existing_nullable=True)
    op.alter_column('google_calendar_tokens', 'access_token',
               existing_type=sa.TEXT(),
               comment='Token de acceso de OAuth (encriptar en producción)',
               existing_nullable=False)
    op.alter_column('google_calendar_tokens', 'doctor_id',
               existing_type=sa.INTEGER(),
               comment='ID del doctor que conectó su Google Calendar',
               existing_nullable=False)
    op.create_table_comment(
        'google_calendar_event_mappings',
        'Mapea citas del sistema con eventos de Google Calendar',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_google_event_mappings_google_event_id', 'google_calendar_event_mappings', ['google_event_id'], unique=False)
    op.create_index('idx_google_event_mappings_doctor_id', 'google_calendar_event_mappings', ['doctor_id'], unique=False)
    op.create_index('idx_google_event_mappings_appointment_id', 'google_calendar_event_mappings', ['appointment_id'], unique=False)
    op.alter_column('google_calendar_event_mappings', 'doctor_id',
               existing_type=sa.INTEGER(),
               comment='ID del doctor propietario del evento',
               existing_nullable=False)
    op.alter_column('google_calendar_event_mappings', 'google_event_id',
               existing_type=sa.VARCHAR(length=255),
               comment='ID del evento en Google Calendar',
               existing_nullable=False)
    op.alter_column('google_calendar_event_mappings', 'appointment_id',
               existing_type=sa.INTEGER(),
               comment='ID de la cita en el sistema',
               existing_nullable=False)
    op.create_table_comment(
        'emergency_relationships',
        'Relaciones familiares para contactos de emergencia',
        existing_comment=None,
        schema=None
    )
    op.create_unique_constraint('documents_name_document_type_id_key', 'documents', ['name', 'document_type_id'])
    op.drop_constraint(None, 'document_folios', type_='foreignkey')
    op.drop_constraint(None, 'document_folios', type_='foreignkey')
    op.create_foreign_key('document_folios_consultation_id_fkey', 'document_folios', 'medical_records', ['consultation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('document_folios_doctor_id_fkey', 'document_folios', 'persons', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_document_folios_unique_consultation', 'document_folios', ['doctor_id', 'consultation_id', 'document_type'], unique=True)
    op.create_index('idx_document_folios_doctor_type_number', 'document_folios', ['doctor_id', 'document_type', 'folio_number'], unique=False)
    op.drop_constraint(None, 'document_folio_sequences', type_='foreignkey')
    op.create_foreign_key('document_folio_sequences_doctor_id_fkey', 'document_folio_sequences', 'persons', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_document_folio_sequences_doctor_type', 'document_folio_sequences', ['doctor_id', 'document_type'], unique=True)
    op.create_table_comment(
        'diagnosis_catalog',
        'Catálogo de diagnósticos médicos',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_diagnosis_catalog_id'), table_name='diagnosis_catalog')
    op.drop_index(op.f('ix_diagnosis_catalog_created_by'), table_name='diagnosis_catalog')
    op.drop_index(op.f('ix_diagnosis_catalog_code'), table_name='diagnosis_catalog')
    op.create_index('idx_diagnosis_catalog_created_by', 'diagnosis_catalog', ['created_by'], unique=False)
    op.create_index('idx_diagnosis_catalog_code', 'diagnosis_catalog', ['code'], unique=False)
    op.create_unique_constraint('diagnosis_catalog_code_key', 'diagnosis_catalog', ['code'])
    op.alter_column('diagnosis_catalog', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('diagnosis_catalog', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('diagnosis_catalog', 'name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('diagnosis_catalog', 'code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.create_table_comment(
        'countries',
        'Catálogo de países del mundo',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'consultation_vital_signs',
        'Signos vitales por consulta',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'consultation_vital_signs', type_='foreignkey')
    op.create_foreign_key('consultation_vital_signs_consultation_id_fkey', 'consultation_vital_signs', 'medical_records', ['consultation_id'], ['id'], ondelete='CASCADE')
    op.alter_column('consultation_vital_signs', 'vital_sign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('consultation_vital_signs', 'consultation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'consultation_prescriptions', type_='foreignkey')
    op.create_foreign_key('consultation_prescriptions_consultation_id_fkey', 'consultation_prescriptions', 'medical_records', ['consultation_id'], ['id'], ondelete='CASCADE')
    op.alter_column('consultation_prescriptions', 'duration',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('consultation_prescriptions', 'frequency',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('consultation_prescriptions', 'dosage',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('consultation_prescriptions', 'medication_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('consultation_prescriptions', 'consultation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table_comment(
        'clinical_studies',
        'Estudios clínicos realizados',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'clinical_studies', type_='foreignkey')
    op.create_foreign_key('clinical_studies_consultation_id_fkey', 'clinical_studies', 'medical_records', ['consultation_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_clinical_studies_id'), table_name='clinical_studies')
    op.create_index('idx_clinical_studies_patient_id', 'clinical_studies', ['patient_id'], unique=False)
    op.create_index('idx_clinical_studies_patient_doctor', 'clinical_studies', ['patient_id', 'doctor_id'], unique=False)
    op.create_index('idx_clinical_studies_ordered_date', 'clinical_studies', ['ordered_date'], unique=False)
    op.alter_column('clinical_studies', 'file_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('clinical_studies', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'ordered'::character varying"))
    op.alter_column('clinical_studies', 'ordered_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('clinical_studies', 'study_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('clinical_studies', 'study_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.create_table_comment(
        'audit_log',
        'Log de auditoría del sistema',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_audit_log_user_id', 'audit_log', ['user_id'], unique=False)
    op.create_index('idx_audit_log_timestamp_user', 'audit_log', ['timestamp', 'user_id'], unique=False)
    op.create_index('idx_audit_log_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_table_comment(
        'arco_requests',
        'Solicitudes ARCO (LFPDPPP)',
        existing_comment=None,
        schema=None
    )
    op.add_column('appointments', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('duration_minutes', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('priority', sa.VARCHAR(length=20), server_default=sa.text("'normal'::character varying"), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table_comment(
        'appointments',
        'Citas médicas',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_index('idx_appointments_patient_id', 'appointments', ['patient_id'], unique=False)
    op.create_index('idx_appointments_patient_doctor', 'appointments', ['patient_id', 'doctor_id'], unique=False)
    op.create_index('idx_appointments_doctor_id', 'appointments', ['doctor_id'], unique=False)
    op.create_index('idx_appointments_appointment_date', 'appointments', ['appointment_date'], unique=False)
    op.alter_column('appointments', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_table_comment(
        'appointment_reminders',
        'Stores up to 3 automatic reminders per appointment. Each reminder can be enabled/disabled independently and has a custom offset_minutes (time before appointment).',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('unique_appointment_reminder_number', 'appointment_reminders', type_='unique')
    op.create_index('idx_appointment_reminders_whatsapp_message_id', 'appointment_reminders', ['whatsapp_message_id'], unique=False)
    op.create_index('idx_appointment_reminders_enabled_sent', 'appointment_reminders', ['enabled', 'sent'], unique=False, postgresql_where='((enabled = true) AND (sent = false))')
    op.create_index('idx_appointment_reminders_appointment_status', 'appointment_reminders', ['appointment_id'], unique=False, postgresql_where='((enabled = true) AND (sent = false))')
    op.create_index('idx_appointment_reminders_appointment_id', 'appointment_reminders', ['appointment_id'], unique=False)
    op.create_unique_constraint('appointment_reminders_appointment_id_reminder_number_key', 'appointment_reminders', ['appointment_id', 'reminder_number'])
    op.create_table('data_retention_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('retention_period_years', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expiration_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='data_retention_logs_pkey'),
    comment='Audit log for all data retention and anonymization actions'
    )
    # Note: Views v_data_retention_stats and v_data_retention_expiring are not recreated here
    # They should be recreated separately if needed
    # ### end Alembic commands ###

